/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as EmbedRouteImport } from './routes/embed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminDictionariesRouteImport } from './routes/admin/dictionaries'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminSourcesRouteImport } from './routes/admin/sources'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppDynamicsRouteImport } from './routes/app/dynamics'
import { Route as AppEscalationsRouteImport } from './routes/app/escalations'
import { Route as AppRechecksRouteImport } from './routes/app/rechecks'
import { Route as AppRequestAccessRouteImport } from './routes/app/request-access'
import { Route as AppTypesRouteImport } from './routes/app/types'
import { Route as AppUnitsRouteImport } from './routes/app/units'
import { Route as AppUsageRouteImport } from './routes/app/usage'
import { Route as AppYoyRouteImport } from './routes/app/yoy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbedRoute = EmbedRouteImport.update({
  id: '/embed',
  path: '/embed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDictionariesRoute = AdminDictionariesRouteImport.update({
  id: '/dictionaries',
  path: '/dictionaries',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSourcesRoute = AdminSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDynamicsRoute = AppDynamicsRouteImport.update({
  id: '/dynamics',
  path: '/dynamics',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEscalationsRoute = AppEscalationsRouteImport.update({
  id: '/escalations',
  path: '/escalations',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRechecksRoute = AppRechecksRouteImport.update({
  id: '/rechecks',
  path: '/rechecks',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRequestAccessRoute = AppRequestAccessRouteImport.update({
  id: '/request-access',
  path: '/request-access',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTypesRoute = AppTypesRouteImport.update({
  id: '/types',
  path: '/types',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUnitsRoute = AppUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsageRoute = AppUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppYoyRoute = AppYoyRouteImport.update({
  id: '/yoy',
  path: '/yoy',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/embed': typeof EmbedRoute
  '/login': typeof LoginRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/dictionaries': typeof AdminDictionariesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/app/dynamics': typeof AppDynamicsRoute
  '/app/escalations': typeof AppEscalationsRoute
  '/app/rechecks': typeof AppRechecksRoute
  '/app/request-access': typeof AppRequestAccessRoute
  '/app/types': typeof AppTypesRoute
  '/app/units': typeof AppUnitsRoute
  '/app/usage': typeof AppUsageRoute
  '/app/yoy': typeof AppYoyRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/embed': typeof EmbedRoute
  '/login': typeof LoginRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/dictionaries': typeof AdminDictionariesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/app/dynamics': typeof AppDynamicsRoute
  '/app/escalations': typeof AppEscalationsRoute
  '/app/rechecks': typeof AppRechecksRoute
  '/app/request-access': typeof AppRequestAccessRoute
  '/app/types': typeof AppTypesRoute
  '/app/units': typeof AppUnitsRoute
  '/app/usage': typeof AppUsageRoute
  '/app/yoy': typeof AppYoyRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/embed': typeof EmbedRoute
  '/login': typeof LoginRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/dictionaries': typeof AdminDictionariesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/sources': typeof AdminSourcesRoute
  '/app/dynamics': typeof AppDynamicsRoute
  '/app/escalations': typeof AppEscalationsRoute
  '/app/rechecks': typeof AppRechecksRoute
  '/app/request-access': typeof AppRequestAccessRoute
  '/app/types': typeof AppTypesRoute
  '/app/units': typeof AppUnitsRoute
  '/app/usage': typeof AppUsageRoute
  '/app/yoy': typeof AppYoyRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/embed'
    | '/login'
    | '/admin/audit'
    | '/admin/dictionaries'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/sources'
    | '/app/dynamics'
    | '/app/escalations'
    | '/app/rechecks'
    | '/app/request-access'
    | '/app/types'
    | '/app/units'
    | '/app/usage'
    | '/app/yoy'
    | '/admin/'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/embed'
    | '/login'
    | '/admin/audit'
    | '/admin/dictionaries'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/sources'
    | '/app/dynamics'
    | '/app/escalations'
    | '/app/rechecks'
    | '/app/request-access'
    | '/app/types'
    | '/app/units'
    | '/app/usage'
    | '/app/yoy'
    | '/admin'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/embed'
    | '/login'
    | '/admin/audit'
    | '/admin/dictionaries'
    | '/admin/reports'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/sources'
    | '/app/dynamics'
    | '/app/escalations'
    | '/app/rechecks'
    | '/app/request-access'
    | '/app/types'
    | '/app/units'
    | '/app/usage'
    | '/app/yoy'
    | '/admin/'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  EmbedRoute: typeof EmbedRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embed': {
      id: '/embed'
      path: '/embed'
      fullPath: '/embed'
      preLoaderRoute: typeof EmbedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/dictionaries': {
      id: '/admin/dictionaries'
      path: '/dictionaries'
      fullPath: '/admin/dictionaries'
      preLoaderRoute: typeof AdminDictionariesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/sources': {
      id: '/admin/sources'
      path: '/sources'
      fullPath: '/admin/sources'
      preLoaderRoute: typeof AdminSourcesRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dynamics': {
      id: '/app/dynamics'
      path: '/dynamics'
      fullPath: '/app/dynamics'
      preLoaderRoute: typeof AppDynamicsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/escalations': {
      id: '/app/escalations'
      path: '/escalations'
      fullPath: '/app/escalations'
      preLoaderRoute: typeof AppEscalationsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/rechecks': {
      id: '/app/rechecks'
      path: '/rechecks'
      fullPath: '/app/rechecks'
      preLoaderRoute: typeof AppRechecksRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/request-access': {
      id: '/app/request-access'
      path: '/request-access'
      fullPath: '/app/request-access'
      preLoaderRoute: typeof AppRequestAccessRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/types': {
      id: '/app/types'
      path: '/types'
      fullPath: '/app/types'
      preLoaderRoute: typeof AppTypesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/units': {
      id: '/app/units'
      path: '/units'
      fullPath: '/app/units'
      preLoaderRoute: typeof AppUnitsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/usage': {
      id: '/app/usage'
      path: '/usage'
      fullPath: '/app/usage'
      preLoaderRoute: typeof AppUsageRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/yoy': {
      id: '/app/yoy'
      path: '/yoy'
      fullPath: '/app/yoy'
      preLoaderRoute: typeof AppYoyRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAuditRoute: typeof AdminAuditRoute
  AdminDictionariesRoute: typeof AdminDictionariesRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSourcesRoute: typeof AdminSourcesRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditRoute: AdminAuditRoute,
  AdminDictionariesRoute: AdminDictionariesRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSourcesRoute: AdminSourcesRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppDynamicsRoute: typeof AppDynamicsRoute
  AppEscalationsRoute: typeof AppEscalationsRoute
  AppRechecksRoute: typeof AppRechecksRoute
  AppRequestAccessRoute: typeof AppRequestAccessRoute
  AppTypesRoute: typeof AppTypesRoute
  AppUnitsRoute: typeof AppUnitsRoute
  AppUsageRoute: typeof AppUsageRoute
  AppYoyRoute: typeof AppYoyRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDynamicsRoute: AppDynamicsRoute,
  AppEscalationsRoute: AppEscalationsRoute,
  AppRechecksRoute: AppRechecksRoute,
  AppRequestAccessRoute: AppRequestAccessRoute,
  AppTypesRoute: AppTypesRoute,
  AppUnitsRoute: AppUnitsRoute,
  AppUsageRoute: AppUsageRoute,
  AppYoyRoute: AppYoyRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  EmbedRoute: EmbedRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
