-- GENERATED by fixtures/generate.ts - do not edit by hand.
-- Synthetic dictionaries for the fixture warehouse (ADR-008 §10).
-- Ids are identity columns: every later file resolves rows BY CODE.
-- Migration 0002 inserts the same UNASSIGNED / `other` sentinels, so
-- every statement is ON CONFLICT (code) DO NOTHING and the two files
-- may be applied in either order.

BEGIN;

-- ── Faculties ──────────────────────────────────────────────────────────
INSERT INTO faculties (code, name_ru, name_kk, name_en) VALUES
    ('FAC01', 'Инженерная академия', 'Инженерлік академия', 'Engineering Academy'),
    ('FAC02', 'Факультет компьютерных наук', 'Компьютерлік ғылымдар факультеті', 'Faculty of Computer Science'),
    ('FAC03', 'Факультет естественных наук', 'Жаратылыстану ғылымдары факультеті', 'Faculty of Natural Sciences'),
    ('FAC04', 'Гуманитарно-педагогический факультет', 'Гуманитарлық-педагогикалық факультет', 'Faculty of Humanities and Education'),
    ('FAC05', 'Факультет экономики и права', 'Экономика және құқық факультеті', 'Faculty of Economics and Law'),
    ('FAC06', 'Аграрно-технологический факультет', 'Аграрлық-технологиялық факультет', 'Faculty of Agriculture and Technology'),
    ('FAC07', 'Архитектурно-строительный факультет', 'Сәулет-құрылыс факультеті', 'Faculty of Architecture and Construction'),
    ('FAC08', 'Факультет искусства и спорта', 'Өнер және спорт факультеті', 'Faculty of Arts and Sport'),
    ('UNASSIGNED', 'Не распределено', 'Бөлінбеген', 'Unassigned')
ON CONFLICT (code) DO NOTHING;

-- ── Departments ────────────────────────────────────────────────────────
INSERT INTO departments (faculty_id, code, name_ru, name_kk, name_en)
SELECT f.id, d.code, d.name_ru, d.name_kk, d.name_en
FROM (VALUES
    ('FAC01', 'DEP01', 'Кафедра «Машиностроение и стандартизация»', '«Машина жасау және стандарттау» кафедрасы', 'Department of Mechanical Engineering and Standardisation'),
    ('FAC01', 'DEP02', 'Кафедра «Электроэнергетика»', '«Электр энергетикасы» кафедрасы', 'Department of Electric Power Engineering'),
    ('FAC01', 'DEP03', 'Кафедра «Транспортная техника»', '«Көлік техникасы» кафедрасы', 'Department of Transport Engineering'),
    ('FAC01', 'DEP04', 'Кафедра «Металлургия»', '«Металлургия» кафедрасы', 'Department of Metallurgy'),
    ('FAC01', 'DEP05', 'Кафедра «Автоматизация и телекоммуникации»', '«Автоматтандыру және телекоммуникация» кафедрасы', 'Department of Automation and Telecommunications'),
    ('FAC02', 'DEP06', 'Кафедра «Вычислительная техника»', '«Есептеу техникасы» кафедрасы', 'Department of Computer Engineering'),
    ('FAC02', 'DEP07', 'Кафедра «Информационные системы»', '«Ақпараттық жүйелер» кафедрасы', 'Department of Information Systems'),
    ('FAC02', 'DEP08', 'Кафедра «Программная инженерия»', '«Бағдарламалық инженерия» кафедрасы', 'Department of Software Engineering'),
    ('FAC02', 'DEP09', 'Кафедра «Кибербезопасность»', '«Киберқауіпсіздік» кафедрасы', 'Department of Cybersecurity'),
    ('FAC02', 'DEP10', 'Кафедра «Прикладная математика»', '«Қолданбалы математика» кафедрасы', 'Department of Applied Mathematics'),
    ('FAC03', 'DEP11', 'Кафедра «Биология и экология»', '«Биология және экология» кафедрасы', 'Department of Biology and Ecology'),
    ('FAC03', 'DEP12', 'Кафедра «Химия и химические технологии»', '«Химия және химиялық технологиялар» кафедрасы', 'Department of Chemistry and Chemical Technology'),
    ('FAC03', 'DEP13', 'Кафедра «Физика и приборостроение»', '«Физика және аспап жасау» кафедрасы', 'Department of Physics and Instrumentation'),
    ('FAC03', 'DEP14', 'Кафедра «География и туризм»', '«География және туризм» кафедрасы', 'Department of Geography and Tourism'),
    ('FAC03', 'DEP15', 'Кафедра «Геология и разведка»', '«Геология және барлау» кафедрасы', 'Department of Geology and Exploration'),
    ('FAC04', 'DEP16', 'Кафедра «Педагогика и методика»', '«Педагогика және әдістеме» кафедрасы', 'Department of Pedagogy and Teaching Methods'),
    ('FAC04', 'DEP17', 'Кафедра «Казахская филология»', '«Қазақ филологиясы» кафедрасы', 'Department of Kazakh Philology'),
    ('FAC04', 'DEP18', 'Кафедра «Иностранная филология»', '«Шетел филологиясы» кафедрасы', 'Department of Foreign Philology'),
    ('FAC04', 'DEP19', 'Кафедра «История и археология»', '«Тарих және археология» кафедрасы', 'Department of History and Archaeology'),
    ('FAC04', 'DEP20', 'Кафедра «Психология и социальная работа»', '«Психология және әлеуметтік жұмыс» кафедрасы', 'Department of Psychology and Social Work'),
    ('FAC05', 'DEP21', 'Кафедра «Экономика и финансы»', '«Экономика және қаржы» кафедрасы', 'Department of Economics and Finance'),
    ('FAC05', 'DEP22', 'Кафедра «Учёт и аудит»', '«Есеп және аудит» кафедрасы', 'Department of Accounting and Audit'),
    ('FAC05', 'DEP23', 'Кафедра «Менеджмент и маркетинг»', '«Менеджмент және маркетинг» кафедрасы', 'Department of Management and Marketing'),
    ('FAC05', 'DEP24', 'Кафедра «Юриспруденция»', '«Құқықтану» кафедрасы', 'Department of Jurisprudence'),
    ('FAC05', 'DEP25', 'Кафедра «Государственное управление»', '«Мемлекеттік басқару» кафедрасы', 'Department of Public Administration'),
    ('FAC06', 'DEP26', 'Кафедра «Агрономия»', '«Агрономия» кафедрасы', 'Department of Agronomy'),
    ('FAC06', 'DEP27', 'Кафедра «Ветеринария»', '«Ветеринария» кафедрасы', 'Department of Veterinary Medicine'),
    ('FAC06', 'DEP28', 'Кафедра «Технология пищевых производств»', '«Тағам өндірісінің технологиясы» кафедрасы', 'Department of Food Production Technology'),
    ('FAC06', 'DEP29', 'Кафедра «Зоотехния»', '«Зоотехния» кафедрасы', 'Department of Animal Science'),
    ('FAC06', 'DEP30', 'Кафедра «Землеустройство»', '«Жерге орналастыру» кафедрасы', 'Department of Land Management'),
    ('FAC07', 'DEP31', 'Кафедра «Архитектура»', '«Сәулет» кафедрасы', 'Department of Architecture'),
    ('FAC07', 'DEP32', 'Кафедра «Строительство»', '«Құрылыс» кафедрасы', 'Department of Civil Engineering'),
    ('FAC07', 'DEP33', 'Кафедра «Дизайн среды»', '«Орта дизайны» кафедрасы', 'Department of Environmental Design'),
    ('FAC07', 'DEP34', 'Кафедра «Инженерные системы»', '«Инженерлік жүйелер» кафедрасы', 'Department of Building Services Engineering'),
    ('FAC07', 'DEP35', 'Кафедра «Градостроительство»', '«Қала құрылысы» кафедрасы', 'Department of Urban Planning'),
    ('FAC08', 'DEP36', 'Кафедра «Музыкальное образование»', '«Музыкалық білім» кафедрасы', 'Department of Music Education'),
    ('FAC08', 'DEP37', 'Кафедра «Изобразительное искусство»', '«Бейнелеу өнері» кафедрасы', 'Department of Fine Arts'),
    ('FAC08', 'DEP38', 'Кафедра «Физическая культура»', '«Дене шынықтыру» кафедрасы', 'Department of Physical Education'),
    ('FAC08', 'DEP39', 'Кафедра «Спортивные дисциплины»', '«Спорт пәндері» кафедрасы', 'Department of Sport Disciplines'),
    ('FAC08', 'DEP40', 'Кафедра «Театр и режиссура»', '«Театр және режиссура» кафедрасы', 'Department of Theatre and Directing'),
    ('UNASSIGNED', 'UNASSIGNED', 'Не распределено', 'Бөлінбеген', 'Unassigned')
) AS d(faculty_code, code, name_ru, name_kk, name_en)
JOIN faculties f ON f.code = d.faculty_code
ON CONFLICT (code) DO NOTHING;

-- ── Programmes (ОП is not derivable from the legacy export; PLAN §1.1) ─
INSERT INTO programs (department_id, code, name_ru, name_kk, name_en)
SELECT dep.id, p.code, p.name_ru, p.name_kk, p.name_en
FROM (VALUES
    ('DEP01', 'PROG01', '6B07101 - Машиностроение', '6B07101 - Машина жасау', '6B07101 - Mechanical Engineering'),
    ('DEP08', 'PROG02', '6B06103 - Программная инженерия', '6B06103 - Бағдарламалық инженерия', '6B06103 - Software Engineering'),
    ('DEP11', 'PROG03', '6B05101 - Биология', '6B05101 - Биология', '6B05101 - Biology'),
    ('DEP17', 'PROG04', '6B01701 - Казахский язык и литература', '6B01701 - Қазақ тілі мен әдебиеті', '6B01701 - Kazakh Language and Literature'),
    ('DEP21', 'PROG05', '6B04101 - Экономика', '6B04101 - Экономика', '6B04101 - Economics'),
    ('DEP26', 'PROG06', '6B08101 - Агрономия', '6B08101 - Агрономия', '6B08101 - Agronomy')
) AS p(department_code, code, name_ru, name_kk, name_en)
JOIN departments dep ON dep.code = p.department_code
ON CONFLICT (code) DO NOTHING;

-- ── Work types (TZ §4.2 §3 + the `other` fallback) ─────────────────────
INSERT INTO work_types (code, name_ru, name_kk, name_en, sort_order) VALUES
    ('course', 'Курсовая работа', 'Курстық жұмыс', 'Course paper', 10),
    ('thesis_bachelor', 'Дипломная работа (ВКР)', 'Дипломдық жұмыс', 'Bachelor thesis', 20),
    ('thesis_master', 'Магистерская диссертация', 'Магистрлік диссертация', 'Master thesis', 30),
    ('thesis_phd', 'Докторская диссертация (PhD)', 'Докторлық диссертация (PhD)', 'PhD thesis', 40),
    ('article', 'Статья ППС', 'ПОҚ мақаласы', 'Faculty article', 50),
    ('research_report', 'Научно-исследовательская работа (НИР)', 'Ғылыми-зерттеу жұмысы', 'Research report', 60),
    ('other', 'Иное', 'Өзге', 'Other', 90)
ON CONFLICT (code) DO NOTHING;

COMMIT;
