-- GENERATED by fixtures/generate.ts - do not edit by hand.
-- Reviewer-e-mail → initiator role (ADR-008 §5), by priority:
--   1. domain teachers.tou.edu.kz          → staff_self
--   2. local part starts with registrar/reg. → registrar
--   3. otherwise                            → other (implicit fallback)
-- Matched against the never-persisted e-mail during parsing.

BEGIN;

INSERT INTO initiator_rules (pattern, initiator, priority, active)
SELECT r.pattern, r.initiator::initiator_role, r.priority, TRUE
FROM (VALUES
    ('@teachers.tou.edu.kz', 'staff_self', 10),
    ('^registrar', 'registrar', 20),
    ('^reg\.', 'registrar', 21)
) AS r(pattern, initiator, priority)
WHERE NOT EXISTS (
    SELECT 1 FROM initiator_rules x WHERE x.pattern = r.pattern
);

COMMIT;
