-- GENERATED by fixtures/generate.ts - do not edit by hand.
-- Title-substring → work type (ADR-008 §7). Case-insensitive match
-- against norm(Название документа); first match by (priority, pattern)
-- wins; no match → `other` / «иное», which therefore has no rule row.
-- `work_type_rules` has no natural unique key, so re-seeding is guarded
-- by NOT EXISTS rather than ON CONFLICT - running this twice is a no-op
-- and it never deletes rules an administrator added.

BEGIN;

INSERT INTO work_type_rules (pattern, work_type_id, priority, active)
SELECT r.pattern, wt.id, r.priority, TRUE
FROM (VALUES
    ('докторская диссертация', 'thesis_phd', 10),
    ('диссертация phd', 'thesis_phd', 11),
    ('докторлық диссертация', 'thesis_phd', 12),
    ('магистерская диссертация', 'thesis_master', 20),
    ('магистрлік диссертация', 'thesis_master', 21),
    ('выпускная квалификационная работа', 'thesis_bachelor', 30),
    ('дипломная работа', 'thesis_bachelor', 31),
    ('дипломный проект', 'thesis_bachelor', 32),
    ('дипломдық жұмыс', 'thesis_bachelor', 33),
    ('курсовая работа', 'course', 40),
    ('курсовой проект', 'course', 41),
    ('курстық жұмыс', 'course', 42),
    ('научная статья', 'article', 50),
    ('статья ппс', 'article', 51),
    ('тезисы доклада', 'article', 52),
    ('научно-исследовательская работа', 'research_report', 60),
    ('отчет по нир', 'research_report', 61),
    ('отчёт по нир', 'research_report', 62)
) AS r(pattern, work_type_code, priority)
JOIN work_types wt ON wt.code = r.work_type_code
WHERE NOT EXISTS (
    SELECT 1 FROM work_type_rules x
    WHERE x.pattern = r.pattern AND x.work_type_id = wt.id
);

COMMIT;
