//! Password hashing and verification (ADR-017 §4).
//!
//! Argon2id with the `argon2` crate's defaults (19 MiB, 2 passes, 1 lane - the
//! RFC 9106 second recommended parameter set). The output is a PHC string, so
//! the parameters travel with every stored hash and raising them later leaves
//! existing accounts verifiable rather than locked out.
//!
//! Two rules hold everywhere in this module:
//!
//! 1. **A missing hash never verifies.** [`verify`] takes an `Option`, and
//!    `None` is a failure, not a skip. An account created without a password
//!    therefore cannot sign in, which is what every row migration 0006
//!    backfilled from the SSO era starts as.
//! 2. **A malformed stored hash is a failure, not a panic.** `unwrap`/`expect`
//!    are clippy-denied in this crate and a corrupt column must not take the
//!    process down.

use argon2::{Argon2, PasswordHash, PasswordHasher, PasswordVerifier};

/// Shortest password the CLI will hash.
///
/// NIST SP 800-63B §5.1.1.2: length is the control that matters, and composition
/// rules are the one that does not. Twelve characters with no character-class
/// requirement is the whole policy; the accounts behind it are a handful of
/// named administrators, not a public sign-up.
pub const MIN_PASSWORD_LENGTH: usize = 12;

/// Longest password accepted. Argon2 itself has no meaningful limit; this one
/// exists so a request body cannot ask the server to hash a megabyte.
pub const MAX_PASSWORD_LENGTH: usize = 256;

#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum PasswordError {
    #[error("a password must be at least {MIN_PASSWORD_LENGTH} characters")]
    TooShort,
    #[error("a password must be at most {MAX_PASSWORD_LENGTH} characters")]
    TooLong,
    #[error("the password could not be hashed")]
    Hashing,
}

/// Reject the two shapes that must never reach the hasher.
///
/// Length is counted in `char`s, not bytes: a Cyrillic passphrase must not be
/// judged twice as long as it reads.
pub fn check_strength(password: &str) -> Result<(), PasswordError> {
    let length = password.chars().count();
    if length < MIN_PASSWORD_LENGTH {
        return Err(PasswordError::TooShort);
    }
    if length > MAX_PASSWORD_LENGTH {
        return Err(PasswordError::TooLong);
    }
    Ok(())
}

/// Hash a password into a PHC string, after [`check_strength`].
///
/// The salt is generated by `argon2` itself, from the operating-system CSPRNG -
/// the same source the session ids come from, and for the same reason.
pub fn hash(password: &str) -> Result<String, PasswordError> {
    check_strength(password)?;
    Argon2::default()
        .hash_password(password.as_bytes())
        .map(|hash| hash.to_string())
        .map_err(|error| {
            tracing::error!(%error, "password hashing failed");
            PasswordError::Hashing
        })
}

/// Verify a candidate against a stored PHC string.
///
/// `stored` is `None` for an account that cannot sign in - one with no password
/// set, or one the caller withheld the hash for because it is deactivated. Both
/// are a **failure**, and both still spend [`spend_verification_time`]: an
/// answer that comes back in microseconds where a wrong password takes tens of
/// milliseconds is a timing oracle, and "this account is disabled" is exactly
/// what it would leak.
///
/// The comparison itself is constant time inside `argon2`; what this function
/// adds is that every negative outcome - no account, no password, deactivated,
/// wrong password - costs the same and returns the same `false`, so the sign-in
/// route has nothing finer to leak.
#[must_use]
pub fn verify(password: &str, stored: Option<&str>) -> bool {
    match stored {
        Some(stored) => verify_against(password, stored),
        None => {
            spend_verification_time();
            false
        }
    }
}

/// The verification itself, against a hash that is known to be present.
///
/// Split out of [`verify`] so that [`spend_verification_time`] can call it
/// without recursing back through the `None` arm - which it would otherwise do
/// forever on the day the decoy failed to hash.
fn verify_against(password: &str, stored: &str) -> bool {
    let Ok(parsed) = PasswordHash::new(stored) else {
        // A column that is not a PHC string is corruption or a hand edit.
        // Refusing the sign-in is the safe reading; the operator resets the
        // password with the CLI. No membership is leaked by answering early
        // here: the account exists either way.
        tracing::error!("stored password hash is not a readable PHC string");
        return false;
    };
    matches!(
        Argon2::default().verify_password(password.as_bytes(), &parsed),
        Ok(())
    )
}

/// The work one failed sign-in costs, spent even when no account matched.
///
/// Without it, "unknown user" answers in microseconds and "wrong password"
/// answers in the tens of milliseconds it takes to run Argon2 - which is a
/// timing oracle for *which login names exist*. Verifying against a fixed hash
/// of a value nobody can supply spends the same time on both paths.
pub fn spend_verification_time() {
    // Hashed once on the first failed sign-in rather than written out as a
    // literal: a hand-typed PHC string that fails to *parse* would return from
    // `verify_against` early and spend no time at all, which is the bug this
    // function exists to prevent.
    static DECOY: std::sync::OnceLock<Option<String>> = std::sync::OnceLock::new();
    if let Some(decoy) = DECOY
        .get_or_init(|| hash("decoy for constant-time sign-in").ok())
        .as_deref()
    {
        let _ = verify_against("", decoy);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_hash_verifies_against_its_own_password_and_nothing_else() {
        let stored = hash("correct horse battery").expect("hashing succeeds");
        assert!(verify("correct horse battery", Some(&stored)));
        assert!(!verify("correct horse batterz", Some(&stored)));
        assert!(!verify("", Some(&stored)));
    }

    /// The stored value is a PHC string carrying its own parameters, not a bare
    /// digest - that is what lets the cost be raised without a flag day.
    #[test]
    fn the_stored_form_is_an_argon2id_phc_string() {
        let stored = hash("correct horse battery").expect("hashing succeeds");
        assert!(stored.starts_with("$argon2id$"), "{stored}");
        assert!(stored.contains("v=19"), "{stored}");
    }

    /// Two accounts that chose the same password must not share a hash, or the
    /// column becomes a lookup table.
    #[test]
    fn the_salt_makes_two_hashes_of_one_password_differ() {
        let first = hash("correct horse battery").expect("hashing succeeds");
        let second = hash("correct horse battery").expect("hashing succeeds");
        assert_ne!(first, second);
        assert!(verify("correct horse battery", Some(&first)));
        assert!(verify("correct horse battery", Some(&second)));
    }

    /// An account with no password set is not an account that signs in with an
    /// empty one.
    #[test]
    fn an_absent_or_corrupt_hash_never_verifies() {
        assert!(!verify("anything", None));
        assert!(!verify("", None));
        assert!(!verify("anything", Some("")));
        assert!(!verify("anything", Some("not-a-phc-string")));
        assert!(!verify("anything", Some("$argon2id$v=19$m=1,t=1,p=1$AAAA")));
    }

    #[test]
    fn length_is_the_whole_policy_and_it_is_counted_in_characters() {
        assert_eq!(check_strength("short"), Err(PasswordError::TooShort));
        // Eleven Cyrillic characters is short; thirteen is not. Counting bytes
        // would have accepted the first at twenty-two.
        assert_eq!(check_strength("паролькорот"), Err(PasswordError::TooShort));
        assert_eq!(check_strength("парольдлинный"), Ok(()));
        assert_eq!(check_strength("123456789012"), Ok(()));
        assert_eq!(
            check_strength(&"x".repeat(MAX_PASSWORD_LENGTH + 1)),
            Err(PasswordError::TooLong)
        );
        assert!(hash("short").is_err());
    }

    /// The decoy must be a *readable* PHC string, or the failed-sign-in path
    /// would return early on a parse error and spend no time at all.
    ///
    /// The `None` case is the one that matters most: a deactivated account
    /// reaches `verify` with its hash withheld, and answering that faster than
    /// a wrong password would announce which accounts are disabled.
    #[test]
    fn every_refusal_costs_the_same_work_as_a_real_verification() {
        let real = hash("correct horse battery").expect("hashing succeeds");
        // Warm the decoy so the first measurement below is not paying for it.
        spend_verification_time();

        let baseline = std::time::Instant::now();
        assert!(!verify("wrong password here", Some(&real)));
        let real_cost = baseline.elapsed();

        let baseline = std::time::Instant::now();
        spend_verification_time();
        let decoy_cost = baseline.elapsed();

        let baseline = std::time::Instant::now();
        assert!(!verify("wrong password here", None));
        let absent_cost = baseline.elapsed();

        // Same order of magnitude, not the same nanosecond: this asserts the
        // work actually runs rather than being skipped.
        for (label, cost) in [("decoy", decoy_cost), ("absent hash", absent_cost)] {
            assert!(
                cost * 10 > real_cost,
                "{label} cost {cost:?} is not comparable to a real verification {real_cost:?}"
            );
        }
    }
}
