/**
 * НЕ РЕДАКТИРОВАТЬ - сгенерировано командой `vp run gen:api` из
 * contracts/openapi.json, который, в свою очередь, генерируется из типов Rust API
 * (ADR-003). Правки вручную перезаписываются при следующем запуске и роняют шлюз
 * рассогласования `gen:api:check`. Измените типы Rust и перегенерируйте.
 */
// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientOptions, type Config, createClient, createConfig } from './client';
import type { ClientOptions as ClientOptions2 } from './types.gen';

/**
 * The `createClientConfig()` function will be called on client initialization
 * and the returned object will become the client's initial configuration.
 *
 * You may want to initialize your client this way instead of calling
 * `setConfig()`. This is useful for example if you're using Next.js
 * to ensure your client always has the correct values.
 */
export type CreateClientConfig<T extends ClientOptions = ClientOptions2> = (override?: Config<ClientOptions & T>) => Config<Required<ClientOptions> & T>;

export const client: Client = createClient(createConfig<ClientOptions2>());
