/**
 * НЕ РЕДАКТИРОВАТЬ - сгенерировано командой `vp run gen:api` из
 * contracts/openapi.json, который, в свою очередь, генерируется из типов Rust API
 * (ADR-003). Правки вручную перезаписываются при следующем запуске и роняют шлюз
 * рассогласования `gen:api:check`. Измените типы Rust и перегенерируйте.
 */
// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * One account and its grants.
 *
 * `email` and `display_name` come from the portal IdP and identify a *service*
 * account of the dashboard, which TZ §6.1 exempts from the PII ban precisely
 * so that grants can be administered. They appear here and nowhere else - no
 * analytic response, no export, no log line.
 */
export type AccountDto = {
    active: boolean;
    display_name: string;
    email: string;
    id: number;
    roles: Array<RoleGrantDto>;
    sso_subject: string;
};

export type AdminPing = {
    scope: ScopeDto;
    sso_subject: string;
};

export type AdminReportDto = {
    generated_at: string;
    has_pdf: boolean;
    has_xlsx: boolean;
    id: number;
    /**
     * `annual` or `manual`.
     */
    kind: string;
    period_end: string;
    period_start: string;
    published: boolean;
};

export type AdminReportsResponse = {
    items: Array<AdminReportDto>;
};

export type AliasDto = {
    id: number;
    /**
     * `faculty`, `department`, `program` or `work_type`.
     */
    kind: string;
    /**
     * The label the source system emits.
     */
    source_label: string;
    target_id: number;
};

export type AliasUpsert = {
    /**
     * `faculty`, `department`, `program` or `work_type`.
     */
    kind: string;
    source_label: string;
    /**
     * Dictionary code the label maps onto.
     */
    target_code: string;
};

export type AliasesResponse = {
    items: Array<AliasDto>;
};

export type AuditResponse = {
    /**
     * The complete action vocabulary, for the filter control.
     */
    actions: Array<string>;
    items: Array<AuditRowDto>;
    /**
     * TZ §6.3 - the retention floor, in days. There is no deletion job.
     */
    retention_days: number;
    total: number;
};

export type AuditRowDto = {
    /**
     * `view`, `export_pdf`, `export_xlsx` or `admin_change`.
     */
    action: string;
    /**
     * Normalized filter state, plus a `change` summary on an admin write.
     */
    filters: unknown;
    id: number;
    ip?: string | null;
    /**
     * RFC 3339 instant.
     */
    occurred_at: string;
    role: string;
    /**
     * Dashboard section or admin area.
     */
    section: string;
    user_id: number;
};

export type BatchDetailDto = BatchDto & {
    /**
     * Per-row rejections, verbatim from `ingest_batches.errors`. Carries a
     * record index, a kind and a contract column label - never source text
     * (AGENTS.md invariant #1).
     */
    errors: unknown;
};

export type BatchDto = {
    finished_at?: string | null;
    id: number;
    /**
     * `api` or `csv`.
     */
    mode: string;
    rows_read: number;
    rows_rejected: number;
    /**
     * «Удален» rows, a policy exclusion rather than a data defect.
     */
    rows_skipped_deleted: number;
    rows_upserted: number;
    source: string;
    started_at: string;
    /**
     * `running`, `succeeded` or `failed`.
     */
    status: string;
};

export type BatchesResponse = {
    items: Array<BatchDto>;
    total: number;
};

export type BreakdownItemDto = {
    avg_originality: ScreenedFloat;
    checks: ScreenedInt;
    /**
     * Dictionary code (work-type or faculty).
     */
    code: string;
    name_en: string;
    name_kk: string;
    name_ru: string;
};

export type BreakdownResponse = {
    items: Array<BreakdownItemDto>;
    k_threshold: number;
    period: PeriodDto;
    /**
     * Cube cells this response withheld because they held fewer than `k`
     * checks (ADR-016 §2). A count, never a size: it makes «недостаточно
     * данных» explicit (TZ §8) without saying how small any group was.
     */
    suppressed_groups: number;
    /**
     * Grand total over the published rows: the sum of exactly the cells the
     * rows are built from, so `Σ items = total` holds on the wire.
     */
    total: MetricPair;
};

export type DepartmentsMatrix = {
    faculties: Array<MatrixFaculty>;
    k_threshold: number;
    period: PeriodDto;
    scope: ScopeDto;
    total: InternalPair;
};

/**
 * Development sign-in request.
 *
 * No name and no e-mail: the identity is the opaque SSO subject, and the
 * synthetic account fields are derived from it, so this endpoint cannot be
 * used to put a person's name into the database (AGENTS.md invariant #1).
 */
export type DevLoginRequest = {
    /**
     * Role to grant: `staff`, `dept_head`, `dean`, `ethics`, `compliance` or
     * `admin`. Omit to mint the role-less session that the «request access»
     * path uses.
     */
    role?: string | null;
    /**
     * Department dictionary code for a `dept_head` grant.
     */
    scope_department_code?: string | null;
    /**
     * Faculty dictionary code for a `dean` grant.
     */
    scope_faculty_code?: string | null;
    /**
     * Opaque subject identifier, as the IdP would supply.
     */
    sso_subject: string;
};

export type DevLoginResponse = {
    /**
     * Hex CSRF token for this session - send it as `x-csrf-token` on every
     * mutating request.
     */
    csrf_token: string;
    /**
     * Grants the account now holds.
     */
    roles: Array<RoleGrantDto>;
    scope?: null | ScopeDto;
    sso_subject: string;
};

export type DictionaryItem = {
    active: boolean;
    code: string;
    name_en: string;
    name_kk: string;
    name_ru: string;
    /**
     * Parent unit code: the faculty of a department, the department of a
     * programme. `null` for faculties and work types.
     */
    parent_code?: string | null;
    /**
     * Work types only.
     */
    sort_order?: number | null;
};

export type DictionaryResponse = {
    items: Array<DictionaryItem>;
    kind: string;
};

export type DictionaryUpsert = {
    active?: boolean;
    code: string;
    name_en?: string;
    name_kk: string;
    name_ru: string;
    /**
     * Faculty code for a department, department code for a programme.
     */
    parent_code?: string | null;
    sort_order?: number;
};

export type EscalationUnit = {
    code: string;
    escalated: ScreenedInt;
    name_ru: string;
};

export type EthicsCaseDto = {
    academic_year: number;
    category: string;
    id: number;
    referred: number;
    reviewed_closed: number;
};

export type EthicsCaseUpsert = {
    /**
     * `2024` is AY 2024/25.
     */
    academic_year: number;
    /**
     * Violation category. Aggregated counters only - never a case file and
     * never a person (TZ §4.2 §7).
     */
    category: string;
    referred: number;
    reviewed_closed: number;
};

export type EthicsCasesResponse = {
    items: Array<EthicsCaseDto>;
};

/**
 * One rejected query parameter or body field.
 */
export type FieldError = {
    /**
     * Parameter name, or a `garde` path such as `to` or `items[0].code`.
     */
    field: string;
    message: string;
};

export type GenerateReportRequest = {
    /**
     * `annual` (the Sep 1 – Aug 31 form) or `manual` (an arbitrary period).
     */
    kind?: string;
    /**
     * `ru` (default), `kk` or `en`.
     */
    locale?: string | null;
    /**
     * Inclusive range end, `YYYY-MM-DD`.
     */
    period_end: string;
    /**
     * Inclusive range start, `YYYY-MM-DD`.
     */
    period_start: string;
};

export type Health = {
    /**
     * Seconds since the newest succeeded ingest batch. `null` when the
     * warehouse has never been fed - a fresh install, not a stale one.
     */
    ingest_age_seconds?: number | null;
    /**
     * The freshness budget this deployment enforces.
     */
    ingest_max_age_seconds?: number | null;
    /**
     * `ok`, `ready`, `db_unreachable` or `ingest_stale`.
     */
    status: string;
};

export type HistogramBucketDto = {
    checks: ScreenedInt;
    /**
     * Stable band key: `b_lt50`, `b_50_70`, `b_70_85`, `b_85_95`, `b_ge95`.
     */
    key: string;
    /**
     * Rendered band label, e.g. `70–85`.
     */
    label: string;
    /**
     * Share of the period's checks in this band, 0..=1.
     */
    share: ScreenedFloat;
};

export type HistogramResponse = {
    /**
     * Band edges in percent, from `settings.histogram_buckets`.
     */
    boundaries: Array<number>;
    buckets: Array<HistogramBucketDto>;
    k_threshold: number;
    period: PeriodDto;
    /**
     * Cube cells this response withheld because they held fewer than `k`
     * checks (ADR-016 §2). A count, never a size: it makes «недостаточно
     * данных» explicit (TZ §8) without saying how small any group was.
     */
    suppressed_groups: number;
    total: ScreenedInt;
};

export type InitiatorRuleDto = {
    active: boolean;
    id: number;
    /**
     * `student`, `staff_self`, `registrar` or `other`.
     */
    initiator: string;
    /**
     * Regular expression matched against the normalized reviewer e-mail.
     */
    pattern: string;
    priority: number;
};

export type InitiatorRuleUpsert = {
    active?: boolean;
    /**
     * `student`, `staff_self`, `registrar` or `other`.
     */
    initiator: string;
    pattern: string;
    priority?: number;
};

export type InitiatorRulesResponse = {
    items: Array<InitiatorRuleDto>;
};

export type InternalBreakdown = {
    items: Array<InternalBreakdownItem>;
    k_threshold: number;
    period: PeriodDto;
    scope: ScopeDto;
    total: InternalPair;
};

export type InternalBreakdownItem = {
    avg_originality: ScreenedFloat;
    checks: ScreenedInt;
    code: string;
    name_en: string;
    name_kk: string;
    name_ru: string;
};

export type InternalEscalations = {
    /**
     * Checks flagged «Подозрительный документ» with the mark not cleared,
     * over the whole scope.
     */
    escalated: ScreenedInt;
    /**
     * Share of the scope's checks, 0..=1.
     */
    escalated_share: ScreenedFloat;
    /**
     * Ethics Council counters for the academic years the period touches.
     * A manually maintained register (D11), never derived from `checks` and
     * never summed with `escalated`.
     */
    ethics_cases: Array<EthicsCaseDto>;
    k_threshold: number;
    period: PeriodDto;
    scope: ScopeDto;
    /**
     * **Always k-screened**, whatever the caller's role - TZ §4.2 §7 «без
     * указания конкретных кафедр при малой выборке».
     */
    units: Array<EscalationUnit>;
};

/**
 * The internal-contour filter set: the public dimensions plus the three the
 * internal contour adds (TZ §4.3 «на внутреннем контуре - дополнительно
 * кафедра и ОП»).
 *
 * Accepting `department`/`program` here is not the same as *allowing* them:
 * [`ScopeGuard::narrow`] checks every unit value against the caller's
 * [`compliance::Scope`] before the filters reach SQL, and a value outside it is
 * a `403`, never an empty result set. Answering "no rows" would leak the same
 * fact more slowly - it tells the caller the unit exists and is empty for
 * them, and it makes an out-of-scope probe indistinguishable from a genuinely
 * empty quarter.
 */
export type InternalFilterQuery = {
    /**
     * Department dictionary code.
     */
    department?: string | null;
    /**
     * Faculty dictionary code.
     */
    faculty?: string | null;
    /**
     * Inclusive range start, `YYYY-MM-DD`.
     */
    from?: string | null;
    /**
     * Who initiated the check: `student`, `staff_self`, `registrar`, `other`.
     */
    initiator?: string | null;
    /**
     * Quick period pick: `month`, `semester`, `year` (the default), `3y`,
     * `5y` or `custom`.
     */
    period?: string | null;
    /**
     * Programme (ОП) dictionary code.
     */
    program?: string | null;
    /**
     * Check status: `accepted`, `needs_revision`, `rejected` or `recheck`.
     */
    status?: string | null;
    /**
     * Inclusive range end, `YYYY-MM-DD`.
     */
    to?: string | null;
    /**
     * Work-type dictionary code.
     */
    work_type?: string | null;
};

export type InternalHistogram = {
    /**
     * Band edges in percent, from `settings.histogram_buckets`.
     */
    boundaries: Array<number>;
    buckets: Array<InternalHistogramBucket>;
    k_threshold: number;
    period: PeriodDto;
    scope: ScopeDto;
    total: ScreenedInt;
};

export type InternalHistogramBucket = {
    checks: ScreenedInt;
    key: string;
    label: string;
    share: ScreenedFloat;
};

/**
 * A count and a mean, the pair every section publishes.
 */
export type InternalPair = {
    avg_originality: ScreenedFloat;
    checks: ScreenedInt;
};

/**
 * Who the caller is and what they may see.
 */
export type InternalPing = {
    /**
     * Widest role held - the value written to `audit_log.role`.
     */
    role: string;
    scope: ScopeDto;
    /**
     * `raw` or `screened` - whether this account reads exact numbers inside
     * its scope (ADR-014 §4).
     */
    screening: string;
    sso_subject: string;
};

export type InternalPreviousPeriod = {
    avg_originality: ScreenedFloat;
    escalated: ScreenedInt;
    period: PeriodDto;
    total_checks: ScreenedInt;
};

export type InternalRechecks = {
    improved: ScreenedInt;
    /**
     * Improved ÷ rechecked, 0..=1.
     */
    improved_share: ScreenedFloat;
    k_threshold: number;
    period: PeriodDto;
    /**
     * Rechecked ÷ total, 0..=1.
     */
    recheck_share: ScreenedFloat;
    scope: ScopeDto;
    /**
     * Per-unit rows inside the caller's scope: faculties for a
     * university-wide caller, departments for a dean, empty for a head of
     * department (whose own row is the total above).
     */
    units: Array<RecheckUnit>;
    works_rechecked: ScreenedInt;
    works_total: ScreenedInt;
};

export type InternalSummary = {
    avg_originality: ScreenedFloat;
    below_threshold: ScreenedInt;
    below_threshold_share: ScreenedFloat;
    coverage?: null | ScreenedFloat;
    escalated: ScreenedInt;
    k_threshold: number;
    period: PeriodDto;
    previous: InternalPreviousPeriod;
    scope: ScopeDto;
    total_checks: ScreenedInt;
};

export type InternalTimeseries = {
    k_threshold: number;
    months: Array<InternalTimeseriesPoint>;
    period: PeriodDto;
    scope: ScopeDto;
};

export type InternalTimeseriesPoint = {
    avg_originality: ScreenedFloat;
    checks: ScreenedInt;
    /**
     * First day of the month, `YYYY-MM-DD`.
     */
    month: string;
};

export type InternalUsage = {
    k_threshold: number;
    months: Array<UsageMonth>;
    period: PeriodDto;
    scope: ScopeDto;
};

export type InternalYoy = {
    k_threshold: number;
    period: PeriodDto;
    scope: ScopeDto;
    total: InternalPair;
    years: Array<InternalYoyYear>;
};

export type InternalYoyYear = {
    /**
     * `2024` is AY 2024/25 (Sep 1 – Aug 31).
     */
    academic_year: number;
    avg_originality: ScreenedFloat;
    checks: ScreenedInt;
    label: string;
};

export type LogoutResponse = {
    /**
     * RP-initiated logout URL, when the provider advertises an
     * `end_session_endpoint`. The browser should follow it so the portal
     * session ends too; `null` means the local session was all there was.
     */
    end_session_url?: string | null;
};

export type MatrixDepartment = {
    avg_originality: ScreenedFloat;
    checks: ScreenedInt;
    code: string;
    name_en: string;
    name_kk: string;
    name_ru: string;
};

export type MatrixFaculty = {
    code: string;
    departments: Array<MatrixDepartment>;
    name_en: string;
    name_kk: string;
    name_ru: string;
    /**
     * The faculty margin - the sum of its visible and hidden departments.
     */
    total: InternalPair;
};

export type MeResponse = {
    /**
     * Hex CSRF token for this session, so a reloaded page can keep mutating.
     */
    csrf_token: string;
    /**
     * Where to send an account that holds no grants (TZ §5).
     */
    request_access_path: string;
    /**
     * Widest role held, or `null` for an account awaiting access.
     */
    role?: string | null;
    roles: Array<RoleGrantDto>;
    scope?: null | ScopeDto;
    sso_subject: string;
};

/**
 * Count and mean originality of one group - the pair every section publishes.
 */
export type MetricPair = {
    /**
     * Mean originality in percent, rounded to 4 decimal places.
     */
    avg_originality: ScreenedFloat;
    checks: ScreenedInt;
};

/**
 * The inclusive range a response covers, echoed back so a cached body is
 * self-describing.
 */
export type PeriodDto = {
    /**
     * `YYYY-MM-DD`, inclusive.
     */
    from: string;
    /**
     * `YYYY-MM-DD`, inclusive.
     */
    to: string;
};

/**
 * The same KPIs one year earlier, plus the deltas the cards render.
 */
export type PreviousPeriodDto = {
    avg_originality: ScreenedFloat;
    below_threshold: ScreenedInt;
    below_threshold_share: ScreenedFloat;
    /**
     * Current minus previous. Suppressed whenever either side is.
     */
    delta: SummaryDeltaDto;
    escalated: ScreenedInt;
    period: PeriodDto;
    total_checks: ScreenedInt;
};

/**
 * One RFC 7807 problem document.
 */
export type Problem = {
    /**
     * Explanation specific to this occurrence.
     */
    detail?: string | null;
    /**
     * Per-field detail for 422 responses.
     */
    errors?: Array<FieldError>;
    /**
     * Request path this problem occurred on.
     */
    instance?: string | null;
    status: number;
    /**
     * Short, human-readable summary - the same for every occurrence of a type.
     */
    title: string;
    /**
     * Stable problem-type identifier, e.g. `/problems/validation-failed`.
     */
    type: string;
};

/**
 * The public-contour filter set (TZ §4.3 minus the internal dimensions).
 *
 * `department`, `program` and `initiator` are deliberately **not** accepted
 * here. The public contour publishes faculty grain at most (TZ §4.2 §4), so a
 * public request asking for department detail is rejected outright rather than
 * quietly widened - `deny_unknown_fields` turns it into a `422`.
 *
 * **`status` was removed by ADR-016 §3** and is now internal only. The public
 * contour publishes sums over cube cells that hold at least `k` checks; adding
 * status to the cube key shatters the grain - 1 244 sub-`k` groups against a
 * handful at three dimensions, roughly 5 % of all rows - so the filter would
 * buy a dimension at the price of suppressing the data. It reaches this struct
 * as an unknown field and is answered with the same `422` as `department`.
 */
export type PublicFilterQuery = {
    /**
     * Faculty dictionary code.
     */
    faculty?: string | null;
    /**
     * Inclusive range start, `YYYY-MM-DD`. Required when `period=custom`.
     *
     * **Snapped down to the first day of its month** (ADR-016 §1): the public
     * contour answers whole months only, so that walking a window's end by one
     * day cannot isolate a single check. The `period` echoed in the response
     * is the snapped range, not the requested one.
     */
    from?: string | null;
    /**
     * Quick period pick: `month`, `semester`, `year` (academic year, the
     * default), `3y`, `5y` or `custom`. With any preset other than `custom`,
     * `from`/`to` are still validated but the preset determines the range.
     */
    period?: string | null;
    /**
     * Inclusive range end, `YYYY-MM-DD`. Required when `period=custom`.
     *
     * **Snapped up to the last day of its month** (ADR-016 §1); see `from`.
     * The quick picks are already month-aligned, so snapping changes nothing
     * for them.
     */
    to?: string | null;
    /**
     * Work-type dictionary code.
     */
    work_type?: string | null;
};

export type PublicStatus = {
    contour: string;
    /**
     * Demonstrates the screened-cell contract; serializes to a number or the
     * string `"insufficient_data"`.
     */
    example_metric: ScreenedInt;
};

export type RecheckUnit = {
    code: string;
    improved: ScreenedInt;
    name_ru: string;
    recheck_share: ScreenedFloat;
    works_rechecked: ScreenedInt;
    works_total: ScreenedInt;
};

export type ReportFileDto = {
    /**
     * Opaque handle for the download endpoint (slice W3.5).
     */
    download_id: string;
    /**
     * `pdf` or `xlsx`.
     */
    format: string;
};

/**
 * A published annual or manual report (TZ §4.5).
 *
 * Snapshots are already-screened artefacts, so nothing here is a live
 * aggregate. No filesystem path leaves the process: the client gets an opaque
 * `download_id` that slice W3.5 resolves to a stream.
 */
export type ReportSnapshotDto = {
    files: Array<ReportFileDto>;
    /**
     * RFC 3339 instant.
     */
    generated_at: string;
    id: number;
    /**
     * `annual` or `manual`.
     */
    kind: string;
    period: PeriodDto;
};

export type ReportsResponse = {
    items: Array<ReportSnapshotDto>;
};

/**
 * One `(role, scope)` grant, as `/api/auth/me` reports it.
 */
export type RoleGrantDto = {
    /**
     * `staff`, `dept_head`, `dean`, `ethics`, `compliance` or `admin`.
     */
    role: string;
    /**
     * Dictionary code of the scoped department; see `scope_faculty_code`.
     */
    scope_department_code?: string | null;
    scope_department_id?: number | null;
    /**
     * Dictionary code of the scoped faculty, so a client can name the unit a
     * dean governs without resolving an opaque id. `null` for an unscoped
     * grant, and for an id whose dictionary row has been deleted.
     */
    scope_faculty_code?: string | null;
    scope_faculty_id?: number | null;
};

export type RoleGrantRequest = {
    /**
     * `staff`, `dept_head`, `dean`, `ethics`, `compliance` or `admin`.
     */
    role: string;
    scope_department_code?: string | null;
    scope_faculty_code?: string | null;
    /**
     * Opaque SSO subject of the account.
     */
    sso_subject: string;
};

/**
 * One AD group's meaning.
 */
export type RoleMapping = {
    /**
     * Department dictionary code - required for `dept_head`.
     */
    department_code?: string | null;
    /**
     * Faculty dictionary code - required for `dean`.
     */
    faculty_code?: string | null;
    /**
     * AD group name as the IdP spells it in the claim.
     */
    group: string;
    /**
     * `staff`, `dept_head`, `dean`, `ethics`, `compliance` or `admin`.
     */
    role: string;
};

export type RolesResponse = {
    items: Array<AccountDto>;
};

export type RunIngestRequest = {
    /**
     * Source to run, enabled or not.
     */
    source_id: number;
};

export type RunIngestResponse = {
    source_id: number;
    /**
     * Always `started`. The run is asynchronous - poll
     * `/api/admin/ingest/batches` for the batch it opens and its counters.
     */
    status: string;
};

/**
 * The caller's RBAC visibility, as `compliance::Scope` renders on the wire.
 *
 * Carries ids rather than codes because that is what the scope *is*; the UI
 * resolves them through the dictionary endpoints.
 */
export type ScopeDto = {
    department_id?: number | null;
    faculty_id?: number | null;
    /**
     * `all`, `faculty` or `department`.
     */
    kind: string;
};

/**
 * OpenAPI shape of `Screened<f64>`: the value, or the suppression marker.
 */
export type ScreenedFloat = number | SuppressedMarker;

/**
 * OpenAPI shape of `Screened<i64>`: the count, or the suppression marker.
 */
export type ScreenedInt = number | SuppressedMarker;

export type SettingDto = {
    key: string;
    /**
     * RFC 3339 instant.
     */
    updated_at: string;
    /**
     * SSO subject of the administrator who last wrote it.
     */
    updated_by?: string | null;
    value: unknown;
};

export type SettingsResponse = {
    items: Array<SettingDto>;
    /**
     * Keys this build knows how to validate. A key outside this list is
     * refused by `PUT`, so a typo cannot create a setting nothing reads.
     */
    known_keys: Array<string>;
};

/**
 * A partial update: only the keys present are written.
 */
export type SettingsUpdate = {
    [key: string]: unknown;
};

export type SourceDto = {
    /**
     * Base URL for an API source, watched directory for a CSV one.
     */
    base_url?: string | null;
    enabled: boolean;
    /**
     * Whether a pull cursor has been recorded. The cursor value itself is
     * ingest bookkeeping and is not editable here - rewriting it by hand would
     * re-read or skip a window.
     */
    has_cursor: boolean;
    id: number;
    /**
     * `api` or `csv`.
     */
    kind: string;
    schedule?: string | null;
};

export type SourceUpsert = {
    base_url?: string | null;
    enabled?: boolean;
    /**
     * `api` or `csv`. Ignored by `PUT` - a source does not change kind.
     */
    kind?: string | null;
    schedule?: string | null;
};

export type SourcesResponse = {
    items: Array<SourceDto>;
};

export type StaffUnitDto = {
    department_code: string;
    /**
     * Hex of the HMAC digest - an opaque handle, not an address.
     */
    email_hmac: string;
    faculty_code: string;
    /**
     * `z***v.vn@teachers.tou.edu.kz` - masked by construction (ADR-008 §2).
     */
    masked_label: string;
    updated_at: string;
};

export type StaffUnitUpsert = {
    department_code: string;
    /**
     * Reviewer e-mail. **Never stored and never logged**: it is HMAC'd with
     * `APP_INGEST_PEPPER` and masked in this handler, and both the plaintext
     * and the request body are dropped when the handler returns.
     */
    email: string;
    faculty_code: string;
};

export type StaffUnitsResponse = {
    items: Array<StaffUnitDto>;
};

export type SubmissionTotalDto = {
    academic_year: number;
    total_submitted: number;
    work_type_code: string;
};

export type SubmissionTotalUpsert = {
    academic_year: number;
    total_submitted?: number;
    work_type_code: string;
};

export type SubmissionTotalsResponse = {
    items: Array<SubmissionTotalDto>;
};

export type SummaryDeltaDto = {
    avg_originality: ScreenedFloat;
    below_threshold_share: ScreenedFloat;
    escalated: ScreenedInt;
    total_checks: ScreenedInt;
};

export type SummaryResponse = {
    avg_originality: ScreenedFloat;
    below_threshold: ScreenedInt;
    /**
     * Share of checks below `settings.originality_threshold`, 0..=1.
     */
    below_threshold_share: ScreenedFloat;
    coverage?: null | ScreenedFloat;
    escalated: ScreenedInt;
    /**
     * Active k-anonymity threshold, so a client can explain a suppressed cell.
     */
    k_threshold: number;
    period: PeriodDto;
    previous: PreviousPeriodDto;
    /**
     * Cube cells this response withheld because they held fewer than `k`
     * checks (ADR-016 §2). A count, never a size: it makes «недостаточно
     * данных» explicit (TZ §8) without saying how small any group was.
     */
    suppressed_groups: number;
    total_checks: ScreenedInt;
};

/**
 * Wire form of a suppressed cell (TZ §6.2 - «недостаточно данных»).
 */
export type SuppressedMarker = 'insufficient_data';

export type TimeseriesPointDto = {
    avg_originality: ScreenedFloat;
    checks: ScreenedInt;
    /**
     * Checks escalated to Комплаенс - «подозрительный» and not cleared.
     *
     * Additive over the cube exactly as `checks` is, so it is a sum over
     * released cells like every other public number (ADR-016 §2). `/summary`
     * already publishes it for the whole period; this is the same measure at
     * the grain the cube is built on.
     */
    escalated: ScreenedInt;
    /**
     * First day of the month, `YYYY-MM-DD`.
     */
    month: string;
    /**
     * Checks that were not the first attempt on their work (ADR-008 §9).
     */
    rechecks: ScreenedInt;
};

export type TimeseriesResponse = {
    k_threshold: number;
    months: Array<TimeseriesPointDto>;
    period: PeriodDto;
    /**
     * Cube cells this response withheld because they held fewer than `k`
     * checks (ADR-016 §2). A count, never a size: it makes «недостаточно
     * данных» explicit (TZ §8) without saying how small any group was.
     */
    suppressed_groups: number;
};

export type UsageMonth = {
    /**
     * Distinct reviewers active in the month, derived from `reviewer_ref`.
     */
    active_reviewers: ScreenedInt;
    /**
     * From the manual `usage_stats` register; `null` means «нет данных»
     * (ADR-008 §9) - never a zero.
     */
    avg_check_seconds?: number | null;
    /**
     * First day of the month, `YYYY-MM-DD`.
     */
    month: string;
    /**
     * The figure Комплаенс entered by hand, for reconciliation against
     * `active_reviewers`.
     */
    reported_active_users?: number | null;
};

export type UsageStatDto = {
    active_users: number;
    /**
     * `null` means «нет данных» - the vendor export carries no duration.
     */
    avg_check_seconds?: number | null;
    /**
     * First day of the month, `YYYY-MM-DD`.
     */
    period_month: string;
};

export type UsageStatUpsert = {
    active_users?: number;
    avg_check_seconds?: number | null;
    /**
     * Any day in the month; stored as its first day.
     */
    period_month: string;
};

export type UsageStatsResponse = {
    items: Array<UsageStatDto>;
};

export type WorkTypeRuleDto = {
    active: boolean;
    id: number;
    /**
     * Substring matched against the normalized title, which is never stored.
     */
    pattern: string;
    /**
     * Lowest wins.
     */
    priority: number;
    work_type_code: string;
};

export type WorkTypeRuleUpsert = {
    active?: boolean;
    pattern: string;
    priority?: number;
    work_type_code: string;
};

export type WorkTypeRulesResponse = {
    items: Array<WorkTypeRuleDto>;
};

export type YoyResponse = {
    k_threshold: number;
    period: PeriodDto;
    /**
     * Cube cells this response withheld because they held fewer than `k`
     * checks (ADR-016 §2). A count, never a size: it makes «недостаточно
     * данных» explicit (TZ §8) without saying how small any group was.
     */
    suppressed_groups: number;
    total: MetricPair;
    years: Array<YoyYearDto>;
};

export type YoyYearDto = {
    /**
     * `2024` is AY 2024/25 (Sep 1 – Aug 31).
     */
    academic_year: number;
    avg_originality: ScreenedFloat;
    checks: ScreenedInt;
    /**
     * Human label, e.g. `2024–2025`.
     */
    label: string;
};

export type ListAliasesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/aliases';
};

export type ListAliasesErrors = {
    403: Problem;
};

export type ListAliasesError = ListAliasesErrors[keyof ListAliasesErrors];

export type ListAliasesResponses = {
    200: AliasesResponse;
};

export type ListAliasesResponse = ListAliasesResponses[keyof ListAliasesResponses];

export type UpsertAliasData = {
    body: AliasUpsert;
    path?: never;
    query?: never;
    url: '/api/admin/aliases';
};

export type UpsertAliasErrors = {
    403: Problem;
    /**
     * unknown kind or target code
     */
    422: Problem;
};

export type UpsertAliasError = UpsertAliasErrors[keyof UpsertAliasErrors];

export type UpsertAliasResponses = {
    200: AliasesResponse;
};

export type UpsertAliasResponse = UpsertAliasResponses[keyof UpsertAliasResponses];

export type DeleteAliasData = {
    body?: never;
    path: {
        /**
         * alias id
         */
        id: number;
    };
    query?: never;
    url: '/api/admin/aliases/{id}';
};

export type DeleteAliasErrors = {
    403: Problem;
    404: Problem;
};

export type DeleteAliasError = DeleteAliasErrors[keyof DeleteAliasErrors];

export type DeleteAliasResponses = {
    /**
     * removed
     */
    204: void;
};

export type DeleteAliasResponse = DeleteAliasResponses[keyof DeleteAliasResponses];

export type AuditData = {
    body?: never;
    path?: never;
    query?: {
        user_id?: number;
        /**
         * `staff`, `dept_head`, `dean`, `ethics`, `compliance` or `admin`.
         */
        role?: string;
        /**
         * `view`, `export_pdf`, `export_xlsx` or `admin_change`.
         */
        action?: string;
        /**
         * Dashboard section or admin area, as journalled.
         */
        section?: string;
        /**
         * Inclusive lower bound, RFC 3339 or `YYYY-MM-DD`.
         */
        from?: string;
        /**
         * Exclusive upper bound.
         */
        to?: string;
        limit?: number;
        offset?: number;
    };
    url: '/api/admin/audit';
};

export type AuditErrors = {
    403: Problem;
    /**
     * unknown role, action, or a malformed date
     */
    422: Problem;
};

export type AuditError = AuditErrors[keyof AuditErrors];

export type AuditResponses = {
    200: AuditResponse;
};

export type AuditResponse2 = AuditResponses[keyof AuditResponses];

export type ListDictionaryData = {
    body?: never;
    path: {
        /**
         * faculties | departments | programs | work-types
         */
        kind: string;
    };
    query?: never;
    url: '/api/admin/dictionaries/{kind}';
};

export type ListDictionaryErrors = {
    403: Problem;
    /**
     * no such dictionary
     */
    404: Problem;
};

export type ListDictionaryError = ListDictionaryErrors[keyof ListDictionaryErrors];

export type ListDictionaryResponses = {
    200: DictionaryResponse;
};

export type ListDictionaryResponse = ListDictionaryResponses[keyof ListDictionaryResponses];

export type UpsertDictionaryData = {
    body: DictionaryUpsert;
    path: {
        /**
         * faculties | departments | programs | work-types
         */
        kind: string;
    };
    query?: never;
    url: '/api/admin/dictionaries/{kind}';
};

export type UpsertDictionaryErrors = {
    403: Problem;
    404: Problem;
    /**
     * malformed code or unknown parent
     */
    422: Problem;
};

export type UpsertDictionaryError = UpsertDictionaryErrors[keyof UpsertDictionaryErrors];

export type UpsertDictionaryResponses = {
    200: DictionaryResponse;
};

export type UpsertDictionaryResponse = UpsertDictionaryResponses[keyof UpsertDictionaryResponses];

export type DeleteDictionaryData = {
    body?: never;
    path: {
        /**
         * faculties | departments | programs | work-types
         */
        kind: string;
        /**
         * dictionary code
         */
        code: string;
    };
    query?: never;
    url: '/api/admin/dictionaries/{kind}/{code}';
};

export type DeleteDictionaryErrors = {
    403: Problem;
    /**
     * no such dictionary or code
     */
    404: Problem;
    /**
     * still referenced by checks or child rows
     */
    409: Problem;
};

export type DeleteDictionaryError = DeleteDictionaryErrors[keyof DeleteDictionaryErrors];

export type DeleteDictionaryResponses = {
    /**
     * removed
     */
    204: void;
};

export type DeleteDictionaryResponse = DeleteDictionaryResponses[keyof DeleteDictionaryResponses];

export type ListEthicsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Inclusive first academic year. Defaults to ten years back.
         */
        from_year?: number;
        to_year?: number;
    };
    url: '/api/admin/ethics-cases';
};

export type ListEthicsErrors = {
    403: Problem;
};

export type ListEthicsError = ListEthicsErrors[keyof ListEthicsErrors];

export type ListEthicsResponses = {
    200: EthicsCasesResponse;
};

export type ListEthicsResponse = ListEthicsResponses[keyof ListEthicsResponses];

export type CreateEthicsData = {
    body: EthicsCaseUpsert;
    path?: never;
    query?: never;
    url: '/api/admin/ethics-cases';
};

export type CreateEthicsErrors = {
    403: Problem;
    422: Problem;
};

export type CreateEthicsError = CreateEthicsErrors[keyof CreateEthicsErrors];

export type CreateEthicsResponses = {
    200: EthicsCasesResponse;
};

export type CreateEthicsResponse = CreateEthicsResponses[keyof CreateEthicsResponses];

export type DeleteEthicsData = {
    body?: never;
    path: {
        /**
         * case id
         */
        id: number;
    };
    query?: never;
    url: '/api/admin/ethics-cases/{id}';
};

export type DeleteEthicsErrors = {
    403: Problem;
    404: Problem;
};

export type DeleteEthicsError = DeleteEthicsErrors[keyof DeleteEthicsErrors];

export type DeleteEthicsResponses = {
    /**
     * removed
     */
    204: void;
};

export type DeleteEthicsResponse = DeleteEthicsResponses[keyof DeleteEthicsResponses];

export type UpdateEthicsData = {
    body: EthicsCaseUpsert;
    path: {
        /**
         * case id
         */
        id: number;
    };
    query?: never;
    url: '/api/admin/ethics-cases/{id}';
};

export type UpdateEthicsErrors = {
    403: Problem;
    404: Problem;
    422: Problem;
};

export type UpdateEthicsError = UpdateEthicsErrors[keyof UpdateEthicsErrors];

export type UpdateEthicsResponses = {
    200: EthicsCasesResponse;
};

export type UpdateEthicsResponse = UpdateEthicsResponses[keyof UpdateEthicsResponses];

export type ListBatchesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Rows per page, at most 500.
         */
        limit?: number;
        offset?: number;
    };
    url: '/api/admin/ingest/batches';
};

export type ListBatchesErrors = {
    403: Problem;
};

export type ListBatchesError = ListBatchesErrors[keyof ListBatchesErrors];

export type ListBatchesResponses = {
    200: BatchesResponse;
};

export type ListBatchesResponse = ListBatchesResponses[keyof ListBatchesResponses];

export type GetBatchData = {
    body?: never;
    path: {
        /**
         * batch id
         */
        id: number;
    };
    query?: never;
    url: '/api/admin/ingest/batches/{id}';
};

export type GetBatchErrors = {
    403: Problem;
    404: Problem;
};

export type GetBatchError = GetBatchErrors[keyof GetBatchErrors];

export type GetBatchResponses = {
    200: BatchDetailDto;
};

export type GetBatchResponse = GetBatchResponses[keyof GetBatchResponses];

export type RunIngestData = {
    body: RunIngestRequest;
    path?: never;
    query?: never;
    url: '/api/admin/ingest/run';
};

export type RunIngestErrors = {
    403: Problem;
    /**
     * no such source
     */
    404: Problem;
    /**
     * the ingest environment is incomplete
     */
    503: Problem;
};

export type RunIngestError = RunIngestErrors[keyof RunIngestErrors];

export type RunIngestResponses = {
    /**
     * run started
     */
    202: RunIngestResponse;
};

export type RunIngestResponse2 = RunIngestResponses[keyof RunIngestResponses];

export type ListSourcesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/ingest/sources';
};

export type ListSourcesErrors = {
    403: Problem;
};

export type ListSourcesError = ListSourcesErrors[keyof ListSourcesErrors];

export type ListSourcesResponses = {
    200: SourcesResponse;
};

export type ListSourcesResponse = ListSourcesResponses[keyof ListSourcesResponses];

export type CreateSourceData = {
    body: SourceUpsert;
    path?: never;
    query?: never;
    url: '/api/admin/ingest/sources';
};

export type CreateSourceErrors = {
    403: Problem;
    /**
     * kind must be api or csv
     */
    422: Problem;
};

export type CreateSourceError = CreateSourceErrors[keyof CreateSourceErrors];

export type CreateSourceResponses = {
    200: SourcesResponse;
};

export type CreateSourceResponse = CreateSourceResponses[keyof CreateSourceResponses];

export type DeleteSourceData = {
    body?: never;
    path: {
        /**
         * source id
         */
        id: number;
    };
    query?: never;
    url: '/api/admin/ingest/sources/{id}';
};

export type DeleteSourceErrors = {
    403: Problem;
    404: Problem;
};

export type DeleteSourceError = DeleteSourceErrors[keyof DeleteSourceErrors];

export type DeleteSourceResponses = {
    /**
     * removed
     */
    204: void;
};

export type DeleteSourceResponse = DeleteSourceResponses[keyof DeleteSourceResponses];

export type UpdateSourceData = {
    body: SourceUpsert;
    path: {
        /**
         * source id
         */
        id: number;
    };
    query?: never;
    url: '/api/admin/ingest/sources/{id}';
};

export type UpdateSourceErrors = {
    403: Problem;
    404: Problem;
};

export type UpdateSourceError = UpdateSourceErrors[keyof UpdateSourceErrors];

export type UpdateSourceResponses = {
    200: SourcesResponse;
};

export type UpdateSourceResponse = UpdateSourceResponses[keyof UpdateSourceResponses];

export type ListInitiatorRulesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/initiator-rules';
};

export type ListInitiatorRulesErrors = {
    403: Problem;
};

export type ListInitiatorRulesError = ListInitiatorRulesErrors[keyof ListInitiatorRulesErrors];

export type ListInitiatorRulesResponses = {
    200: InitiatorRulesResponse;
};

export type ListInitiatorRulesResponse = ListInitiatorRulesResponses[keyof ListInitiatorRulesResponses];

export type CreateInitiatorRuleData = {
    body: InitiatorRuleUpsert;
    path?: never;
    query?: never;
    url: '/api/admin/initiator-rules';
};

export type CreateInitiatorRuleErrors = {
    403: Problem;
    /**
     * unknown role or a pattern that does not compile
     */
    422: Problem;
};

export type CreateInitiatorRuleError = CreateInitiatorRuleErrors[keyof CreateInitiatorRuleErrors];

export type CreateInitiatorRuleResponses = {
    200: InitiatorRulesResponse;
};

export type CreateInitiatorRuleResponse = CreateInitiatorRuleResponses[keyof CreateInitiatorRuleResponses];

export type DeleteInitiatorRuleData = {
    body?: never;
    path: {
        /**
         * rule id
         */
        id: number;
    };
    query?: never;
    url: '/api/admin/initiator-rules/{id}';
};

export type DeleteInitiatorRuleErrors = {
    403: Problem;
    404: Problem;
};

export type DeleteInitiatorRuleError = DeleteInitiatorRuleErrors[keyof DeleteInitiatorRuleErrors];

export type DeleteInitiatorRuleResponses = {
    /**
     * removed
     */
    204: void;
};

export type DeleteInitiatorRuleResponse = DeleteInitiatorRuleResponses[keyof DeleteInitiatorRuleResponses];

export type UpdateInitiatorRuleData = {
    body: InitiatorRuleUpsert;
    path: {
        /**
         * rule id
         */
        id: number;
    };
    query?: never;
    url: '/api/admin/initiator-rules/{id}';
};

export type UpdateInitiatorRuleErrors = {
    403: Problem;
    404: Problem;
    422: Problem;
};

export type UpdateInitiatorRuleError = UpdateInitiatorRuleErrors[keyof UpdateInitiatorRuleErrors];

export type UpdateInitiatorRuleResponses = {
    200: InitiatorRulesResponse;
};

export type UpdateInitiatorRuleResponse = UpdateInitiatorRuleResponses[keyof UpdateInitiatorRuleResponses];

export type PingData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/ping';
};

export type PingErrors = {
    /**
     * no valid session
     */
    401: Problem;
    /**
     * not an administrator
     */
    403: Problem;
};

export type PingError = PingErrors[keyof PingErrors];

export type PingResponses = {
    200: AdminPing;
};

export type PingResponse = PingResponses[keyof PingResponses];

export type ListReportsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Rows per page, at most 500.
         */
        limit?: number;
        offset?: number;
    };
    url: '/api/admin/reports';
};

export type ListReportsErrors = {
    403: Problem;
};

export type ListReportsError = ListReportsErrors[keyof ListReportsErrors];

export type ListReportsResponses = {
    200: AdminReportsResponse;
};

export type ListReportsResponse = ListReportsResponses[keyof ListReportsResponses];

export type GenerateReportData = {
    body: GenerateReportRequest;
    path?: never;
    query?: never;
    url: '/api/admin/reports/generate';
};

export type GenerateReportErrors = {
    403: Problem;
    /**
     * malformed period, kind or locale
     */
    422: Problem;
};

export type GenerateReportError = GenerateReportErrors[keyof GenerateReportErrors];

export type GenerateReportResponses = {
    /**
     * generated
     */
    201: AdminReportsResponse;
};

export type GenerateReportResponse = GenerateReportResponses[keyof GenerateReportResponses];

export type PublishReportData = {
    body?: never;
    path: {
        /**
         * snapshot id
         */
        id: number;
    };
    query?: never;
    url: '/api/admin/reports/{id}/publish';
};

export type PublishReportErrors = {
    403: Problem;
    404: Problem;
};

export type PublishReportError = PublishReportErrors[keyof PublishReportErrors];

export type PublishReportResponses = {
    /**
     * published
     */
    204: void;
};

export type PublishReportResponse = PublishReportResponses[keyof PublishReportResponses];

export type UnpublishReportData = {
    body?: never;
    path: {
        /**
         * snapshot id
         */
        id: number;
    };
    query?: never;
    url: '/api/admin/reports/{id}/unpublish';
};

export type UnpublishReportErrors = {
    403: Problem;
    404: Problem;
};

export type UnpublishReportError = UnpublishReportErrors[keyof UnpublishReportErrors];

export type UnpublishReportResponses = {
    /**
     * withdrawn
     */
    204: void;
};

export type UnpublishReportResponse = UnpublishReportResponses[keyof UnpublishReportResponses];

export type RevokeRoleData = {
    body: RoleGrantRequest;
    path?: never;
    query?: never;
    url: '/api/admin/roles';
};

export type RevokeRoleErrors = {
    403: Problem;
    /**
     * no such account or grant
     */
    404: Problem;
    422: Problem;
};

export type RevokeRoleError = RevokeRoleErrors[keyof RevokeRoleErrors];

export type RevokeRoleResponses = {
    /**
     * revoked
     */
    204: void;
};

export type RevokeRoleResponse = RevokeRoleResponses[keyof RevokeRoleResponses];

export type ListRolesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Rows per page, at most 500.
         */
        limit?: number;
        offset?: number;
    };
    url: '/api/admin/roles';
};

export type ListRolesErrors = {
    403: Problem;
};

export type ListRolesError = ListRolesErrors[keyof ListRolesErrors];

export type ListRolesResponses = {
    200: RolesResponse;
};

export type ListRolesResponse = ListRolesResponses[keyof ListRolesResponses];

export type GrantRoleData = {
    body: RoleGrantRequest;
    path?: never;
    query?: never;
    url: '/api/admin/roles';
};

export type GrantRoleErrors = {
    403: Problem;
    /**
     * no such account
     */
    404: Problem;
    /**
     * unknown role or unit code
     */
    422: Problem;
};

export type GrantRoleError = GrantRoleErrors[keyof GrantRoleErrors];

export type GrantRoleResponses = {
    200: RolesResponse;
};

export type GrantRoleResponse = GrantRoleResponses[keyof GrantRoleResponses];

export type SettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/settings';
};

export type SettingsErrors = {
    403: Problem;
};

export type SettingsError = SettingsErrors[keyof SettingsErrors];

export type SettingsResponses = {
    200: SettingsResponse;
};

export type SettingsResponse2 = SettingsResponses[keyof SettingsResponses];

export type UpdateSettingsData = {
    body: SettingsUpdate;
    path?: never;
    query?: never;
    url: '/api/admin/settings';
};

export type UpdateSettingsErrors = {
    403: Problem;
    /**
     * unknown key or a value the domain type refuses
     */
    422: Problem;
};

export type UpdateSettingsError = UpdateSettingsErrors[keyof UpdateSettingsErrors];

export type UpdateSettingsResponses = {
    200: SettingsResponse;
};

export type UpdateSettingsResponse = UpdateSettingsResponses[keyof UpdateSettingsResponses];

export type ListStaffUnitsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Rows per page, at most 500.
         */
        limit?: number;
        offset?: number;
    };
    url: '/api/admin/staff-units';
};

export type ListStaffUnitsErrors = {
    403: Problem;
};

export type ListStaffUnitsError = ListStaffUnitsErrors[keyof ListStaffUnitsErrors];

export type ListStaffUnitsResponses = {
    200: StaffUnitsResponse;
};

export type ListStaffUnitsResponse = ListStaffUnitsResponses[keyof ListStaffUnitsResponses];

export type UpsertStaffUnitData = {
    body: StaffUnitUpsert;
    path?: never;
    query?: never;
    url: '/api/admin/staff-units';
};

export type UpsertStaffUnitErrors = {
    403: Problem;
    /**
     * unknown unit code
     */
    422: Problem;
    /**
     * APP_INGEST_PEPPER is not configured on this host
     */
    503: Problem;
};

export type UpsertStaffUnitError = UpsertStaffUnitErrors[keyof UpsertStaffUnitErrors];

export type UpsertStaffUnitResponses = {
    200: StaffUnitsResponse;
};

export type UpsertStaffUnitResponse = UpsertStaffUnitResponses[keyof UpsertStaffUnitResponses];

export type DeleteStaffUnitData = {
    body?: never;
    path: {
        /**
         * hex of the 32-byte HMAC digest
         */
        hmac: string;
    };
    query?: never;
    url: '/api/admin/staff-units/{hmac}';
};

export type DeleteStaffUnitErrors = {
    403: Problem;
    404: Problem;
    /**
     * not a 32-byte hex digest
     */
    422: Problem;
};

export type DeleteStaffUnitError = DeleteStaffUnitErrors[keyof DeleteStaffUnitErrors];

export type DeleteStaffUnitResponses = {
    /**
     * removed
     */
    204: void;
};

export type DeleteStaffUnitResponse = DeleteStaffUnitResponses[keyof DeleteStaffUnitResponses];

export type DeleteSubmissionTotalData = {
    body: SubmissionTotalUpsert;
    path?: never;
    query?: never;
    url: '/api/admin/submission-totals';
};

export type DeleteSubmissionTotalErrors = {
    403: Problem;
    404: Problem;
};

export type DeleteSubmissionTotalError = DeleteSubmissionTotalErrors[keyof DeleteSubmissionTotalErrors];

export type DeleteSubmissionTotalResponses = {
    /**
     * removed
     */
    204: void;
};

export type DeleteSubmissionTotalResponse = DeleteSubmissionTotalResponses[keyof DeleteSubmissionTotalResponses];

export type ListSubmissionTotalsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Inclusive first academic year. Defaults to ten years back.
         */
        from_year?: number;
        to_year?: number;
    };
    url: '/api/admin/submission-totals';
};

export type ListSubmissionTotalsErrors = {
    403: Problem;
};

export type ListSubmissionTotalsError = ListSubmissionTotalsErrors[keyof ListSubmissionTotalsErrors];

export type ListSubmissionTotalsResponses = {
    200: SubmissionTotalsResponse;
};

export type ListSubmissionTotalsResponse = ListSubmissionTotalsResponses[keyof ListSubmissionTotalsResponses];

export type UpsertSubmissionTotalData = {
    body: SubmissionTotalUpsert;
    path?: never;
    query?: never;
    url: '/api/admin/submission-totals';
};

export type UpsertSubmissionTotalErrors = {
    403: Problem;
    /**
     * unknown work type or a negative total
     */
    422: Problem;
};

export type UpsertSubmissionTotalError = UpsertSubmissionTotalErrors[keyof UpsertSubmissionTotalErrors];

export type UpsertSubmissionTotalResponses = {
    200: SubmissionTotalsResponse;
};

export type UpsertSubmissionTotalResponse = UpsertSubmissionTotalResponses[keyof UpsertSubmissionTotalResponses];

export type DeleteUsageStatData = {
    body: UsageStatUpsert;
    path?: never;
    query?: never;
    url: '/api/admin/usage-stats';
};

export type DeleteUsageStatErrors = {
    403: Problem;
    404: Problem;
    422: Problem;
};

export type DeleteUsageStatError = DeleteUsageStatErrors[keyof DeleteUsageStatErrors];

export type DeleteUsageStatResponses = {
    /**
     * removed
     */
    204: void;
};

export type DeleteUsageStatResponse = DeleteUsageStatResponses[keyof DeleteUsageStatResponses];

export type ListUsageStatsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Inclusive first month, `YYYY-MM-DD`. Defaults to five years back.
         */
        from?: string;
        to?: string;
    };
    url: '/api/admin/usage-stats';
};

export type ListUsageStatsErrors = {
    403: Problem;
    422: Problem;
};

export type ListUsageStatsError = ListUsageStatsErrors[keyof ListUsageStatsErrors];

export type ListUsageStatsResponses = {
    200: UsageStatsResponse;
};

export type ListUsageStatsResponse = ListUsageStatsResponses[keyof ListUsageStatsResponses];

export type UpsertUsageStatData = {
    body: UsageStatUpsert;
    path?: never;
    query?: never;
    url: '/api/admin/usage-stats';
};

export type UpsertUsageStatErrors = {
    403: Problem;
    422: Problem;
};

export type UpsertUsageStatError = UpsertUsageStatErrors[keyof UpsertUsageStatErrors];

export type UpsertUsageStatResponses = {
    200: UsageStatsResponse;
};

export type UpsertUsageStatResponse = UpsertUsageStatResponses[keyof UpsertUsageStatResponses];

export type ListWorkTypeRulesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/admin/work-type-rules';
};

export type ListWorkTypeRulesErrors = {
    403: Problem;
};

export type ListWorkTypeRulesError = ListWorkTypeRulesErrors[keyof ListWorkTypeRulesErrors];

export type ListWorkTypeRulesResponses = {
    200: WorkTypeRulesResponse;
};

export type ListWorkTypeRulesResponse = ListWorkTypeRulesResponses[keyof ListWorkTypeRulesResponses];

export type CreateWorkTypeRuleData = {
    body: WorkTypeRuleUpsert;
    path?: never;
    query?: never;
    url: '/api/admin/work-type-rules';
};

export type CreateWorkTypeRuleErrors = {
    403: Problem;
    /**
     * empty pattern or unknown work type
     */
    422: Problem;
};

export type CreateWorkTypeRuleError = CreateWorkTypeRuleErrors[keyof CreateWorkTypeRuleErrors];

export type CreateWorkTypeRuleResponses = {
    200: WorkTypeRulesResponse;
};

export type CreateWorkTypeRuleResponse = CreateWorkTypeRuleResponses[keyof CreateWorkTypeRuleResponses];

export type DeleteWorkTypeRuleData = {
    body?: never;
    path: {
        /**
         * rule id
         */
        id: number;
    };
    query?: never;
    url: '/api/admin/work-type-rules/{id}';
};

export type DeleteWorkTypeRuleErrors = {
    403: Problem;
    404: Problem;
};

export type DeleteWorkTypeRuleError = DeleteWorkTypeRuleErrors[keyof DeleteWorkTypeRuleErrors];

export type DeleteWorkTypeRuleResponses = {
    /**
     * removed
     */
    204: void;
};

export type DeleteWorkTypeRuleResponse = DeleteWorkTypeRuleResponses[keyof DeleteWorkTypeRuleResponses];

export type UpdateWorkTypeRuleData = {
    body: WorkTypeRuleUpsert;
    path: {
        /**
         * rule id
         */
        id: number;
    };
    query?: never;
    url: '/api/admin/work-type-rules/{id}';
};

export type UpdateWorkTypeRuleErrors = {
    403: Problem;
    404: Problem;
    422: Problem;
};

export type UpdateWorkTypeRuleError = UpdateWorkTypeRuleErrors[keyof UpdateWorkTypeRuleErrors];

export type UpdateWorkTypeRuleResponses = {
    200: WorkTypeRulesResponse;
};

export type UpdateWorkTypeRuleResponse = UpdateWorkTypeRuleResponses[keyof UpdateWorkTypeRuleResponses];

export type CallbackData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Authorization code, on success.
         */
        code?: string;
        /**
         * Opaque value echoed back, compared against the flow cookie.
         */
        state?: string;
        /**
         * OAuth error code, when the user declined or the provider refused.
         */
        error?: string;
        error_description?: string;
    };
    url: '/api/auth/callback';
};

export type CallbackErrors = {
    /**
     * the sign-in could not be matched to this browser
     */
    403: Problem;
    /**
     * the identity provider rejected the exchange
     */
    502: Problem;
    /**
     * no identity provider is configured
     */
    503: Problem;
};

export type CallbackError = CallbackErrors[keyof CallbackErrors];

export type DevLoginData = {
    body: DevLoginRequest;
    path?: never;
    query?: never;
    url: '/api/auth/dev-login';
};

export type DevLoginErrors = {
    /**
     * not running in dev auth mode
     */
    404: Problem;
    /**
     * unknown dictionary code
     */
    422: Problem;
};

export type DevLoginError = DevLoginErrors[keyof DevLoginErrors];

export type DevLoginResponses = {
    200: DevLoginResponse;
};

export type DevLoginResponse2 = DevLoginResponses[keyof DevLoginResponses];

export type LoginData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/login';
};

export type LoginErrors = {
    /**
     * no identity provider is configured
     */
    503: Problem;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/logout';
};

export type LogoutErrors = {
    /**
     * no valid session
     */
    401: Problem;
    /**
     * missing or mismatched CSRF token
     */
    403: Problem;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    /**
     * session ended
     */
    200: LogoutResponse;
};

export type LogoutResponse2 = LogoutResponses[keyof LogoutResponses];

export type MeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/auth/me';
};

export type MeErrors = {
    /**
     * no valid session
     */
    401: Problem;
};

export type MeError = MeErrors[keyof MeErrors];

export type MeResponses = {
    200: MeResponse;
};

export type MeResponse2 = MeResponses[keyof MeResponses];

export type DepartmentsMatrixData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Quick period pick: `month`, `semester`, `year` (the default), `3y`,
         * `5y` or `custom`.
         */
        period?: string;
        /**
         * Inclusive range start, `YYYY-MM-DD`.
         */
        from?: string;
        /**
         * Inclusive range end, `YYYY-MM-DD`.
         */
        to?: string;
        /**
         * Faculty dictionary code.
         */
        faculty?: string;
        /**
         * Department dictionary code.
         */
        department?: string;
        /**
         * Programme (ОП) dictionary code.
         */
        program?: string;
        /**
         * Work-type dictionary code.
         */
        work_type?: string;
        /**
         * Check status: `accepted`, `needs_revision`, `rejected` or `recheck`.
         */
        status?: string;
        /**
         * Who initiated the check: `student`, `staff_self`, `registrar`, `other`.
         */
        initiator?: string;
    };
    url: '/api/internal/departments-matrix';
};

export type DepartmentsMatrixErrors = {
    401: Problem;
    403: Problem;
    422: Problem;
};

export type DepartmentsMatrixError = DepartmentsMatrixErrors[keyof DepartmentsMatrixErrors];

export type DepartmentsMatrixResponses = {
    200: DepartmentsMatrix;
};

export type DepartmentsMatrixResponse = DepartmentsMatrixResponses[keyof DepartmentsMatrixResponses];

export type EscalationsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Quick period pick: `month`, `semester`, `year` (the default), `3y`,
         * `5y` or `custom`.
         */
        period?: string;
        /**
         * Inclusive range start, `YYYY-MM-DD`.
         */
        from?: string;
        /**
         * Inclusive range end, `YYYY-MM-DD`.
         */
        to?: string;
        /**
         * Faculty dictionary code.
         */
        faculty?: string;
        /**
         * Department dictionary code.
         */
        department?: string;
        /**
         * Programme (ОП) dictionary code.
         */
        program?: string;
        /**
         * Work-type dictionary code.
         */
        work_type?: string;
        /**
         * Check status: `accepted`, `needs_revision`, `rejected` or `recheck`.
         */
        status?: string;
        /**
         * Who initiated the check: `student`, `staff_self`, `registrar`, `other`.
         */
        initiator?: string;
    };
    url: '/api/internal/escalations';
};

export type EscalationsErrors = {
    401: Problem;
    403: Problem;
    422: Problem;
};

export type EscalationsError = EscalationsErrors[keyof EscalationsErrors];

export type EscalationsResponses = {
    200: InternalEscalations;
};

export type EscalationsResponse = EscalationsResponses[keyof EscalationsResponses];

export type InternalExportData = {
    /**
     * the filter state to export; an empty body means the default period
     */
    body: InternalFilterQuery;
    path?: never;
    query: {
        /**
         * Wire names of the two export formats.
         */
        format: 'pdf' | 'xlsx';
        /**
         * Report language: `ru` (default), `kk` or `en`.
         */
        locale?: string;
    };
    url: '/api/internal/export';
};

export type InternalExportErrors = {
    401: Problem;
    /**
     * role without export rights, a unit outside your scope, or a missing CSRF token
     */
    403: Problem;
    /**
     * malformed filters or format
     */
    422: Problem;
};

export type InternalExportError = InternalExportErrors[keyof InternalExportErrors];

export type InternalExportResponses = {
    /**
     * the rendered report
     */
    200: Blob | File;
};

export type InternalExportResponse = InternalExportResponses[keyof InternalExportResponses];

export type HistogramData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Quick period pick: `month`, `semester`, `year` (the default), `3y`,
         * `5y` or `custom`.
         */
        period?: string;
        /**
         * Inclusive range start, `YYYY-MM-DD`.
         */
        from?: string;
        /**
         * Inclusive range end, `YYYY-MM-DD`.
         */
        to?: string;
        /**
         * Faculty dictionary code.
         */
        faculty?: string;
        /**
         * Department dictionary code.
         */
        department?: string;
        /**
         * Programme (ОП) dictionary code.
         */
        program?: string;
        /**
         * Work-type dictionary code.
         */
        work_type?: string;
        /**
         * Check status: `accepted`, `needs_revision`, `rejected` or `recheck`.
         */
        status?: string;
        /**
         * Who initiated the check: `student`, `staff_self`, `registrar`, `other`.
         */
        initiator?: string;
    };
    url: '/api/internal/histogram';
};

export type HistogramErrors = {
    401: Problem;
    403: Problem;
    422: Problem;
};

export type HistogramError = HistogramErrors[keyof HistogramErrors];

export type HistogramResponses = {
    200: InternalHistogram;
};

export type HistogramResponse2 = HistogramResponses[keyof HistogramResponses];

export type Ping2Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/internal/ping';
};

export type Ping2Errors = {
    /**
     * no valid session
     */
    401: Problem;
    /**
     * no role for the internal contour
     */
    403: Problem;
};

export type Ping2Error = Ping2Errors[keyof Ping2Errors];

export type Ping2Responses = {
    200: InternalPing;
};

export type Ping2Response = Ping2Responses[keyof Ping2Responses];

export type RechecksData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Quick period pick: `month`, `semester`, `year` (the default), `3y`,
         * `5y` or `custom`.
         */
        period?: string;
        /**
         * Inclusive range start, `YYYY-MM-DD`.
         */
        from?: string;
        /**
         * Inclusive range end, `YYYY-MM-DD`.
         */
        to?: string;
        /**
         * Faculty dictionary code.
         */
        faculty?: string;
        /**
         * Department dictionary code.
         */
        department?: string;
        /**
         * Programme (ОП) dictionary code.
         */
        program?: string;
        /**
         * Work-type dictionary code.
         */
        work_type?: string;
        /**
         * Check status: `accepted`, `needs_revision`, `rejected` or `recheck`.
         */
        status?: string;
        /**
         * Who initiated the check: `student`, `staff_self`, `registrar`, `other`.
         */
        initiator?: string;
    };
    url: '/api/internal/rechecks';
};

export type RechecksErrors = {
    401: Problem;
    403: Problem;
    422: Problem;
};

export type RechecksError = RechecksErrors[keyof RechecksErrors];

export type RechecksResponses = {
    200: InternalRechecks;
};

export type RechecksResponse = RechecksResponses[keyof RechecksResponses];

export type SummaryData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Quick period pick: `month`, `semester`, `year` (the default), `3y`,
         * `5y` or `custom`.
         */
        period?: string;
        /**
         * Inclusive range start, `YYYY-MM-DD`.
         */
        from?: string;
        /**
         * Inclusive range end, `YYYY-MM-DD`.
         */
        to?: string;
        /**
         * Faculty dictionary code.
         */
        faculty?: string;
        /**
         * Department dictionary code.
         */
        department?: string;
        /**
         * Programme (ОП) dictionary code.
         */
        program?: string;
        /**
         * Work-type dictionary code.
         */
        work_type?: string;
        /**
         * Check status: `accepted`, `needs_revision`, `rejected` or `recheck`.
         */
        status?: string;
        /**
         * Who initiated the check: `student`, `staff_self`, `registrar`, `other`.
         */
        initiator?: string;
    };
    url: '/api/internal/summary';
};

export type SummaryErrors = {
    401: Problem;
    /**
     * no internal role, or a unit filter outside your scope
     */
    403: Problem;
    /**
     * malformed filters
     */
    422: Problem;
};

export type SummaryError = SummaryErrors[keyof SummaryErrors];

export type SummaryResponses = {
    200: InternalSummary;
};

export type SummaryResponse2 = SummaryResponses[keyof SummaryResponses];

export type TimeseriesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Quick period pick: `month`, `semester`, `year` (the default), `3y`,
         * `5y` or `custom`.
         */
        period?: string;
        /**
         * Inclusive range start, `YYYY-MM-DD`.
         */
        from?: string;
        /**
         * Inclusive range end, `YYYY-MM-DD`.
         */
        to?: string;
        /**
         * Faculty dictionary code.
         */
        faculty?: string;
        /**
         * Department dictionary code.
         */
        department?: string;
        /**
         * Programme (ОП) dictionary code.
         */
        program?: string;
        /**
         * Work-type dictionary code.
         */
        work_type?: string;
        /**
         * Check status: `accepted`, `needs_revision`, `rejected` or `recheck`.
         */
        status?: string;
        /**
         * Who initiated the check: `student`, `staff_self`, `registrar`, `other`.
         */
        initiator?: string;
    };
    url: '/api/internal/timeseries';
};

export type TimeseriesErrors = {
    401: Problem;
    403: Problem;
    422: Problem;
};

export type TimeseriesError = TimeseriesErrors[keyof TimeseriesErrors];

export type TimeseriesResponses = {
    200: InternalTimeseries;
};

export type TimeseriesResponse2 = TimeseriesResponses[keyof TimeseriesResponses];

export type UsageData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Quick period pick: `month`, `semester`, `year` (the default), `3y`,
         * `5y` or `custom`.
         */
        period?: string;
        /**
         * Inclusive range start, `YYYY-MM-DD`.
         */
        from?: string;
        /**
         * Inclusive range end, `YYYY-MM-DD`.
         */
        to?: string;
        /**
         * Faculty dictionary code.
         */
        faculty?: string;
        /**
         * Department dictionary code.
         */
        department?: string;
        /**
         * Programme (ОП) dictionary code.
         */
        program?: string;
        /**
         * Work-type dictionary code.
         */
        work_type?: string;
        /**
         * Check status: `accepted`, `needs_revision`, `rejected` or `recheck`.
         */
        status?: string;
        /**
         * Who initiated the check: `student`, `staff_self`, `registrar`, `other`.
         */
        initiator?: string;
    };
    url: '/api/internal/usage';
};

export type UsageErrors = {
    401: Problem;
    403: Problem;
    422: Problem;
};

export type UsageError = UsageErrors[keyof UsageErrors];

export type UsageResponses = {
    200: InternalUsage;
};

export type UsageResponse = UsageResponses[keyof UsageResponses];

export type WorkTypesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Quick period pick: `month`, `semester`, `year` (the default), `3y`,
         * `5y` or `custom`.
         */
        period?: string;
        /**
         * Inclusive range start, `YYYY-MM-DD`.
         */
        from?: string;
        /**
         * Inclusive range end, `YYYY-MM-DD`.
         */
        to?: string;
        /**
         * Faculty dictionary code.
         */
        faculty?: string;
        /**
         * Department dictionary code.
         */
        department?: string;
        /**
         * Programme (ОП) dictionary code.
         */
        program?: string;
        /**
         * Work-type dictionary code.
         */
        work_type?: string;
        /**
         * Check status: `accepted`, `needs_revision`, `rejected` or `recheck`.
         */
        status?: string;
        /**
         * Who initiated the check: `student`, `staff_self`, `registrar`, `other`.
         */
        initiator?: string;
    };
    url: '/api/internal/work-types';
};

export type WorkTypesErrors = {
    401: Problem;
    403: Problem;
    422: Problem;
};

export type WorkTypesError = WorkTypesErrors[keyof WorkTypesErrors];

export type WorkTypesResponses = {
    200: InternalBreakdown;
};

export type WorkTypesResponse = WorkTypesResponses[keyof WorkTypesResponses];

export type YoyData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Quick period pick: `month`, `semester`, `year` (the default), `3y`,
         * `5y` or `custom`.
         */
        period?: string;
        /**
         * Inclusive range start, `YYYY-MM-DD`.
         */
        from?: string;
        /**
         * Inclusive range end, `YYYY-MM-DD`.
         */
        to?: string;
        /**
         * Faculty dictionary code.
         */
        faculty?: string;
        /**
         * Department dictionary code.
         */
        department?: string;
        /**
         * Programme (ОП) dictionary code.
         */
        program?: string;
        /**
         * Work-type dictionary code.
         */
        work_type?: string;
        /**
         * Check status: `accepted`, `needs_revision`, `rejected` or `recheck`.
         */
        status?: string;
        /**
         * Who initiated the check: `student`, `staff_self`, `registrar`, `other`.
         */
        initiator?: string;
    };
    url: '/api/internal/yoy';
};

export type YoyErrors = {
    401: Problem;
    403: Problem;
    422: Problem;
};

export type YoyError = YoyErrors[keyof YoyErrors];

export type YoyResponses = {
    200: InternalYoy;
};

export type YoyResponse2 = YoyResponses[keyof YoyResponses];

export type PublicExportData = {
    /**
     * the filter state to export; an empty body means the default period
     */
    body: PublicFilterQuery;
    path?: never;
    query: {
        /**
         * Wire names of the two export formats.
         */
        format: 'pdf' | 'xlsx';
        /**
         * Report language: `ru` (default), `kk` or `en`.
         */
        locale?: string;
    };
    url: '/api/public/export';
};

export type PublicExportErrors = {
    /**
     * malformed filters or format
     */
    422: Problem;
    /**
     * rate limited
     */
    429: Problem;
};

export type PublicExportError = PublicExportErrors[keyof PublicExportErrors];

export type PublicExportResponses = {
    /**
     * the rendered report
     */
    200: Blob | File;
};

export type PublicExportResponse = PublicExportResponses[keyof PublicExportResponses];

export type FacultiesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Quick period pick: `month`, `semester`, `year` (academic year, the
         * default), `3y`, `5y` or `custom`. With any preset other than `custom`,
         * `from`/`to` are still validated but the preset determines the range.
         */
        period?: string;
        /**
         * Inclusive range start, `YYYY-MM-DD`. Required when `period=custom`.
         *
         * **Snapped down to the first day of its month** (ADR-016 §1): the public
         * contour answers whole months only, so that walking a window's end by one
         * day cannot isolate a single check. The `period` echoed in the response
         * is the snapped range, not the requested one.
         */
        from?: string;
        /**
         * Inclusive range end, `YYYY-MM-DD`. Required when `period=custom`.
         *
         * **Snapped up to the last day of its month** (ADR-016 §1); see `from`.
         * The quick picks are already month-aligned, so snapping changes nothing
         * for them.
         */
        to?: string;
        /**
         * Faculty dictionary code.
         */
        faculty?: string;
        /**
         * Work-type dictionary code.
         */
        work_type?: string;
    };
    url: '/api/public/faculties';
};

export type FacultiesErrors = {
    /**
     * malformed filters
     */
    422: Problem;
};

export type FacultiesError = FacultiesErrors[keyof FacultiesErrors];

export type FacultiesResponses = {
    200: BreakdownResponse;
};

export type FacultiesResponse = FacultiesResponses[keyof FacultiesResponses];

export type Histogram2Data = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Quick period pick: `month`, `semester`, `year` (academic year, the
         * default), `3y`, `5y` or `custom`. With any preset other than `custom`,
         * `from`/`to` are still validated but the preset determines the range.
         */
        period?: string;
        /**
         * Inclusive range start, `YYYY-MM-DD`. Required when `period=custom`.
         *
         * **Snapped down to the first day of its month** (ADR-016 §1): the public
         * contour answers whole months only, so that walking a window's end by one
         * day cannot isolate a single check. The `period` echoed in the response
         * is the snapped range, not the requested one.
         */
        from?: string;
        /**
         * Inclusive range end, `YYYY-MM-DD`. Required when `period=custom`.
         *
         * **Snapped up to the last day of its month** (ADR-016 §1); see `from`.
         * The quick picks are already month-aligned, so snapping changes nothing
         * for them.
         */
        to?: string;
        /**
         * Faculty dictionary code.
         */
        faculty?: string;
        /**
         * Work-type dictionary code.
         */
        work_type?: string;
    };
    url: '/api/public/histogram';
};

export type Histogram2Errors = {
    /**
     * malformed filters
     */
    422: Problem;
};

export type Histogram2Error = Histogram2Errors[keyof Histogram2Errors];

export type Histogram2Responses = {
    200: HistogramResponse;
};

export type Histogram2Response = Histogram2Responses[keyof Histogram2Responses];

export type ReportsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/public/reports';
};

export type ReportsResponses = {
    200: ReportsResponse;
};

export type ReportsResponse2 = ReportsResponses[keyof ReportsResponses];

export type DownloadData = {
    body?: never;
    path: {
        /**
         * report snapshot id from /api/public/reports
         */
        id: number;
    };
    query: {
        /**
         * Wire names of the two export formats.
         */
        format: 'pdf' | 'xlsx';
    };
    url: '/api/public/reports/{id}/download';
};

export type DownloadErrors = {
    /**
     * no such published snapshot, or no file in that format
     */
    404: Problem;
};

export type DownloadError = DownloadErrors[keyof DownloadErrors];

export type DownloadResponses = {
    /**
     * the published file
     */
    200: Blob | File;
};

export type DownloadResponse = DownloadResponses[keyof DownloadResponses];

export type StatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/public/status';
};

export type StatusResponses = {
    200: PublicStatus;
};

export type StatusResponse = StatusResponses[keyof StatusResponses];

export type Summary2Data = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Quick period pick: `month`, `semester`, `year` (academic year, the
         * default), `3y`, `5y` or `custom`. With any preset other than `custom`,
         * `from`/`to` are still validated but the preset determines the range.
         */
        period?: string;
        /**
         * Inclusive range start, `YYYY-MM-DD`. Required when `period=custom`.
         *
         * **Snapped down to the first day of its month** (ADR-016 §1): the public
         * contour answers whole months only, so that walking a window's end by one
         * day cannot isolate a single check. The `period` echoed in the response
         * is the snapped range, not the requested one.
         */
        from?: string;
        /**
         * Inclusive range end, `YYYY-MM-DD`. Required when `period=custom`.
         *
         * **Snapped up to the last day of its month** (ADR-016 §1); see `from`.
         * The quick picks are already month-aligned, so snapping changes nothing
         * for them.
         */
        to?: string;
        /**
         * Faculty dictionary code.
         */
        faculty?: string;
        /**
         * Work-type dictionary code.
         */
        work_type?: string;
    };
    url: '/api/public/summary';
};

export type Summary2Errors = {
    /**
     * malformed filters
     */
    422: Problem;
    /**
     * rate limited
     */
    429: Problem;
};

export type Summary2Error = Summary2Errors[keyof Summary2Errors];

export type Summary2Responses = {
    200: SummaryResponse;
};

export type Summary2Response = Summary2Responses[keyof Summary2Responses];

export type Timeseries2Data = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Quick period pick: `month`, `semester`, `year` (academic year, the
         * default), `3y`, `5y` or `custom`. With any preset other than `custom`,
         * `from`/`to` are still validated but the preset determines the range.
         */
        period?: string;
        /**
         * Inclusive range start, `YYYY-MM-DD`. Required when `period=custom`.
         *
         * **Snapped down to the first day of its month** (ADR-016 §1): the public
         * contour answers whole months only, so that walking a window's end by one
         * day cannot isolate a single check. The `period` echoed in the response
         * is the snapped range, not the requested one.
         */
        from?: string;
        /**
         * Inclusive range end, `YYYY-MM-DD`. Required when `period=custom`.
         *
         * **Snapped up to the last day of its month** (ADR-016 §1); see `from`.
         * The quick picks are already month-aligned, so snapping changes nothing
         * for them.
         */
        to?: string;
        /**
         * Faculty dictionary code.
         */
        faculty?: string;
        /**
         * Work-type dictionary code.
         */
        work_type?: string;
    };
    url: '/api/public/timeseries';
};

export type Timeseries2Errors = {
    /**
     * malformed filters
     */
    422: Problem;
};

export type Timeseries2Error = Timeseries2Errors[keyof Timeseries2Errors];

export type Timeseries2Responses = {
    200: TimeseriesResponse;
};

export type Timeseries2Response = Timeseries2Responses[keyof Timeseries2Responses];

export type WorkTypes2Data = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Quick period pick: `month`, `semester`, `year` (academic year, the
         * default), `3y`, `5y` or `custom`. With any preset other than `custom`,
         * `from`/`to` are still validated but the preset determines the range.
         */
        period?: string;
        /**
         * Inclusive range start, `YYYY-MM-DD`. Required when `period=custom`.
         *
         * **Snapped down to the first day of its month** (ADR-016 §1): the public
         * contour answers whole months only, so that walking a window's end by one
         * day cannot isolate a single check. The `period` echoed in the response
         * is the snapped range, not the requested one.
         */
        from?: string;
        /**
         * Inclusive range end, `YYYY-MM-DD`. Required when `period=custom`.
         *
         * **Snapped up to the last day of its month** (ADR-016 §1); see `from`.
         * The quick picks are already month-aligned, so snapping changes nothing
         * for them.
         */
        to?: string;
        /**
         * Faculty dictionary code.
         */
        faculty?: string;
        /**
         * Work-type dictionary code.
         */
        work_type?: string;
    };
    url: '/api/public/work-types';
};

export type WorkTypes2Errors = {
    /**
     * malformed filters
     */
    422: Problem;
};

export type WorkTypes2Error = WorkTypes2Errors[keyof WorkTypes2Errors];

export type WorkTypes2Responses = {
    200: BreakdownResponse;
};

export type WorkTypes2Response = WorkTypes2Responses[keyof WorkTypes2Responses];

export type Yoy2Data = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Quick period pick: `month`, `semester`, `year` (academic year, the
         * default), `3y`, `5y` or `custom`. With any preset other than `custom`,
         * `from`/`to` are still validated but the preset determines the range.
         */
        period?: string;
        /**
         * Inclusive range start, `YYYY-MM-DD`. Required when `period=custom`.
         *
         * **Snapped down to the first day of its month** (ADR-016 §1): the public
         * contour answers whole months only, so that walking a window's end by one
         * day cannot isolate a single check. The `period` echoed in the response
         * is the snapped range, not the requested one.
         */
        from?: string;
        /**
         * Inclusive range end, `YYYY-MM-DD`. Required when `period=custom`.
         *
         * **Snapped up to the last day of its month** (ADR-016 §1); see `from`.
         * The quick picks are already month-aligned, so snapping changes nothing
         * for them.
         */
        to?: string;
        /**
         * Faculty dictionary code.
         */
        faculty?: string;
        /**
         * Work-type dictionary code.
         */
        work_type?: string;
    };
    url: '/api/public/yoy';
};

export type Yoy2Errors = {
    /**
     * malformed filters
     */
    422: Problem;
};

export type Yoy2Error = Yoy2Errors[keyof Yoy2Errors];

export type Yoy2Responses = {
    200: YoyResponse;
};

export type Yoy2Response = Yoy2Responses[keyof Yoy2Responses];

export type HealthzData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type HealthzResponses = {
    200: Health;
};

export type HealthzResponse = HealthzResponses[keyof HealthzResponses];

export type ReadyzData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/readyz';
};

export type ReadyzErrors = {
    /**
     * database unreachable, or the newest ingest batch is stale
     */
    503: Health;
};

export type ReadyzError = ReadyzErrors[keyof ReadyzErrors];

export type ReadyzResponses = {
    200: Health;
};

export type ReadyzResponse = ReadyzResponses[keyof ReadyzResponses];
