/**
 * НЕ РЕДАКТИРОВАТЬ - сгенерировано командой `vp run gen:api` из
 * contracts/openapi.json, который, в свою очередь, генерируется из типов Rust API
 * (ADR-003). Правки вручную перезаписываются при следующем запуске и роняют шлюз
 * рассогласования `gen:api:check`. Измените типы Rust и перегенерируйте.
 */
// This file is auto-generated by @hey-api/openapi-ts

import * as v from 'valibot';

export const vAdminReportDto = v.object({
    generated_at: v.string(),
    has_pdf: v.boolean(),
    has_xlsx: v.boolean(),
    id: v.pipe(v.number(), v.integer()),
    kind: v.string(),
    period_end: v.string(),
    period_start: v.string(),
    published: v.boolean()
});

export const vAdminReportsResponse = v.object({
    items: v.array(vAdminReportDto)
});

export const vAliasDto = v.object({
    id: v.pipe(v.number(), v.integer()),
    kind: v.string(),
    source_label: v.string(),
    target_id: v.pipe(v.number(), v.integer())
});

export const vAliasUpsert = v.strictObject({
    kind: v.string(),
    source_label: v.string(),
    target_code: v.string()
});

export const vAliasesResponse = v.object({
    items: v.array(vAliasDto)
});

export const vAuditRowDto = v.object({
    action: v.string(),
    filters: v.unknown(),
    id: v.pipe(v.number(), v.integer()),
    ip: v.nullish(v.string()),
    occurred_at: v.string(),
    role: v.string(),
    section: v.string(),
    user_id: v.pipe(v.number(), v.integer())
});

export const vAuditResponse = v.object({
    actions: v.array(v.string()),
    items: v.array(vAuditRowDto),
    retention_days: v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    total: v.pipe(v.number(), v.integer())
});

export const vBatchDto = v.object({
    finished_at: v.nullish(v.string()),
    id: v.pipe(v.number(), v.integer()),
    mode: v.string(),
    rows_read: v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    rows_rejected: v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    rows_skipped_deleted: v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    rows_upserted: v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    source: v.string(),
    started_at: v.string(),
    status: v.string()
});

export const vBatchDetailDto = v.intersect([vBatchDto, v.object({
        errors: v.unknown()
    })]);

export const vBatchesResponse = v.object({
    items: v.array(vBatchDto),
    total: v.pipe(v.number(), v.integer())
});

export const vDictionaryItem = v.object({
    active: v.boolean(),
    code: v.string(),
    name_en: v.string(),
    name_kk: v.string(),
    name_ru: v.string(),
    parent_code: v.nullish(v.string()),
    sort_order: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')))
});

export const vDictionaryResponse = v.object({
    items: v.array(vDictionaryItem),
    kind: v.string()
});

export const vDictionaryUpsert = v.strictObject({
    active: v.optional(v.boolean()),
    code: v.string(),
    name_en: v.optional(v.string()),
    name_kk: v.string(),
    name_ru: v.string(),
    parent_code: v.nullish(v.string()),
    sort_order: v.optional(v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')))
});

export const vEthicsCaseDto = v.object({
    academic_year: v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    category: v.string(),
    id: v.pipe(v.number(), v.integer()),
    referred: v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    reviewed_closed: v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647'))
});

export const vEthicsCaseUpsert = v.strictObject({
    academic_year: v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    category: v.string(),
    referred: v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    reviewed_closed: v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647'))
});

export const vEthicsCasesResponse = v.object({
    items: v.array(vEthicsCaseDto)
});

/**
 * One rejected query parameter or body field.
 */
export const vFieldError = v.object({
    field: v.string(),
    message: v.string()
});

export const vGenerateReportRequest = v.strictObject({
    kind: v.optional(v.string()),
    locale: v.nullish(v.string()),
    period_end: v.string(),
    period_start: v.string()
});

export const vHealth = v.object({
    ingest_age_seconds: v.nullish(v.pipe(v.number(), v.integer())),
    ingest_max_age_seconds: v.nullish(v.pipe(v.number(), v.integer())),
    status: v.string()
});

export const vInitiatorRuleDto = v.object({
    active: v.boolean(),
    id: v.pipe(v.number(), v.integer()),
    initiator: v.string(),
    pattern: v.string(),
    priority: v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647'))
});

export const vInitiatorRuleUpsert = v.strictObject({
    active: v.optional(v.boolean()),
    initiator: v.string(),
    pattern: v.string(),
    priority: v.optional(v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')))
});

export const vInitiatorRulesResponse = v.object({
    items: v.array(vInitiatorRuleDto)
});

/**
 * The internal-contour filter set: the public dimensions plus the three the
 * internal contour adds (TZ §4.3 «на внутреннем контуре - дополнительно
 * кафедра и ОП»).
 *
 * Accepting `department`/`program` here is not the same as *allowing* them:
 * [`ScopeGuard::narrow`] checks every unit value against the caller's
 * [`compliance::Scope`] before the filters reach SQL, and a value outside it is
 * a `403`, never an empty result set. Answering "no rows" would leak the same
 * fact more slowly - it tells the caller the unit exists and is empty for
 * them, and it makes an out-of-scope probe indistinguishable from a genuinely
 * empty quarter.
 */
export const vInternalFilterQuery = v.strictObject({
    department: v.nullish(v.string()),
    faculty: v.nullish(v.string()),
    from: v.nullish(v.string()),
    initiator: v.nullish(v.string()),
    period: v.nullish(v.string()),
    program: v.nullish(v.string()),
    status: v.nullish(v.string()),
    to: v.nullish(v.string()),
    work_type: v.nullish(v.string())
});

/**
 * Sign-in request.
 *
 * No name and no e-mail: those are account fields an operator sets with the
 * CLI, so this endpoint cannot be used to put a person's name into the
 * database (AGENTS.md invariant #1).
 */
export const vLoginRequest = v.strictObject({
    password: v.string(),
    username: v.string()
});

export const vLogoutResponse = v.object({
    next_path: v.string()
});

/**
 * The inclusive range a response covers, echoed back so a cached body is
 * self-describing.
 */
export const vPeriodDto = v.object({
    from: v.string(),
    to: v.string()
});

/**
 * One RFC 7807 problem document.
 */
export const vProblem = v.object({
    detail: v.nullish(v.string()),
    errors: v.optional(v.array(vFieldError)),
    instance: v.nullish(v.string()),
    status: v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    title: v.string(),
    type: v.string()
});

/**
 * The public-contour filter set (TZ §4.3 minus the internal dimensions).
 *
 * `department`, `program` and `initiator` are deliberately **not** accepted
 * here. The public contour publishes faculty grain at most (TZ §4.2 §4), so a
 * public request asking for department detail is rejected outright rather than
 * quietly widened - `deny_unknown_fields` turns it into a `422`.
 *
 * **`status` was removed by ADR-016 §3** and is now internal only. The public
 * contour publishes sums over cube cells that hold at least `k` checks; adding
 * status to the cube key shatters the grain - 1 244 sub-`k` groups against a
 * handful at three dimensions, roughly 5 % of all rows - so the filter would
 * buy a dimension at the price of suppressing the data. It reaches this struct
 * as an unknown field and is answered with the same `422` as `department`.
 */
export const vPublicFilterQuery = v.strictObject({
    faculty: v.nullish(v.string()),
    from: v.nullish(v.string()),
    period: v.nullish(v.string()),
    to: v.nullish(v.string()),
    work_type: v.nullish(v.string())
});

export const vReportFileDto = v.object({
    download_id: v.string(),
    format: v.string()
});

/**
 * A published annual or manual report (TZ §4.5).
 *
 * Snapshots are already-screened artefacts, so nothing here is a live
 * aggregate. No filesystem path leaves the process: the client gets an opaque
 * `download_id` that slice W3.5 resolves to a stream.
 */
export const vReportSnapshotDto = v.object({
    files: v.array(vReportFileDto),
    generated_at: v.string(),
    id: v.pipe(v.number(), v.integer()),
    kind: v.string(),
    period: vPeriodDto
});

export const vReportsResponse = v.object({
    items: v.array(vReportSnapshotDto)
});

/**
 * One `(role, scope)` grant, as `/api/auth/me` reports it.
 */
export const vRoleGrantDto = v.object({
    role: v.string(),
    scope_department_code: v.nullish(v.string()),
    scope_department_id: v.nullish(v.pipe(v.number(), v.integer())),
    scope_faculty_code: v.nullish(v.string()),
    scope_faculty_id: v.nullish(v.pipe(v.number(), v.integer()))
});

/**
 * One account and its grants.
 *
 * `email` and `display_name` are set by the operator who created the account
 * with the `manage-users` CLI and identify a *service* account of the
 * dashboard, which TZ §6.1 exempts from the PII ban precisely so that grants
 * can be administered. They appear here and nowhere else - no analytic
 * response, no export, no log line.
 */
export const vAccountDto = v.object({
    active: v.boolean(),
    display_name: v.string(),
    email: v.string(),
    id: v.pipe(v.number(), v.integer()),
    roles: v.array(vRoleGrantDto),
    username: v.string()
});

export const vRoleGrantRequest = v.strictObject({
    role: v.string(),
    scope_department_code: v.nullish(v.string()),
    scope_faculty_code: v.nullish(v.string()),
    username: v.string()
});

export const vRolesResponse = v.object({
    items: v.array(vAccountDto)
});

export const vRunIngestRequest = v.strictObject({
    source_id: v.pipe(v.number(), v.integer())
});

export const vRunIngestResponse = v.object({
    source_id: v.pipe(v.number(), v.integer()),
    status: v.string()
});

/**
 * The caller's RBAC visibility, as `compliance::Scope` renders on the wire.
 *
 * Carries ids rather than codes because that is what the scope *is*; the UI
 * resolves them through the dictionary endpoints.
 */
export const vScopeDto = v.object({
    department_id: v.nullish(v.pipe(v.number(), v.integer())),
    faculty_id: v.nullish(v.pipe(v.number(), v.integer())),
    kind: v.string()
});

export const vAdminPing = v.object({
    scope: vScopeDto,
    username: v.string()
});

/**
 * Who the caller is and what they may see.
 */
export const vInternalPing = v.object({
    role: v.string(),
    scope: vScopeDto,
    screening: v.string(),
    username: v.string()
});

export const vMeResponse = v.object({
    csrf_token: v.string(),
    request_access_path: v.string(),
    role: v.nullish(v.string()),
    roles: v.array(vRoleGrantDto),
    scope: v.nullish(vScopeDto),
    username: v.string()
});

export const vSettingDto = v.object({
    key: v.string(),
    updated_at: v.string(),
    updated_by: v.nullish(v.string()),
    value: v.unknown()
});

export const vSettingsResponse = v.object({
    items: v.array(vSettingDto),
    known_keys: v.array(v.string())
});

/**
 * A partial update: only the keys present are written.
 */
export const vSettingsUpdate = v.record(v.string(), v.unknown());

export const vSourceDto = v.object({
    base_url: v.nullish(v.string()),
    enabled: v.boolean(),
    has_cursor: v.boolean(),
    id: v.pipe(v.number(), v.integer()),
    kind: v.string(),
    schedule: v.nullish(v.string())
});

export const vSourceUpsert = v.strictObject({
    base_url: v.nullish(v.string()),
    enabled: v.optional(v.boolean()),
    kind: v.nullish(v.string()),
    schedule: v.nullish(v.string())
});

export const vSourcesResponse = v.object({
    items: v.array(vSourceDto)
});

export const vStaffUnitDto = v.object({
    department_code: v.string(),
    email_hmac: v.string(),
    faculty_code: v.string(),
    masked_label: v.string(),
    updated_at: v.string()
});

export const vStaffUnitUpsert = v.strictObject({
    department_code: v.string(),
    email: v.string(),
    faculty_code: v.string()
});

export const vStaffUnitsResponse = v.object({
    items: v.array(vStaffUnitDto)
});

export const vSubmissionTotalDto = v.object({
    academic_year: v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    total_submitted: v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    work_type_code: v.string()
});

export const vSubmissionTotalUpsert = v.strictObject({
    academic_year: v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    total_submitted: v.optional(v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647'))),
    work_type_code: v.string()
});

export const vSubmissionTotalsResponse = v.object({
    items: v.array(vSubmissionTotalDto)
});

/**
 * Wire form of a suppressed cell (TZ §6.2 - «недостаточно данных»).
 */
export const vSuppressedMarker = v.picklist(['insufficient_data']);

/**
 * OpenAPI shape of `Screened<f64>`: the value, or the suppression marker.
 */
export const vScreenedFloat = v.union([v.number(), vSuppressedMarker]);

/**
 * OpenAPI shape of `Screened<i64>`: the count, or the suppression marker.
 */
export const vScreenedInt = v.union([v.pipe(v.number(), v.integer()), vSuppressedMarker]);

export const vBreakdownItemDto = v.object({
    avg_originality: vScreenedFloat,
    checks: vScreenedInt,
    code: v.string(),
    name_en: v.string(),
    name_kk: v.string(),
    name_ru: v.string()
});

export const vEscalationUnit = v.object({
    code: v.string(),
    escalated: vScreenedInt,
    name_ru: v.string()
});

export const vHistogramBucketDto = v.object({
    checks: vScreenedInt,
    key: v.string(),
    label: v.string(),
    share: vScreenedFloat
});

export const vHistogramResponse = v.object({
    boundaries: v.array(v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647'))),
    buckets: v.array(vHistogramBucketDto),
    k_threshold: v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    period: vPeriodDto,
    suppressed_groups: v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    total: vScreenedInt
});

export const vInternalBreakdownItem = v.object({
    avg_originality: vScreenedFloat,
    checks: vScreenedInt,
    code: v.string(),
    name_en: v.string(),
    name_kk: v.string(),
    name_ru: v.string()
});

export const vInternalEscalations = v.object({
    escalated: vScreenedInt,
    escalated_share: vScreenedFloat,
    ethics_cases: v.array(vEthicsCaseDto),
    k_threshold: v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    period: vPeriodDto,
    scope: vScopeDto,
    units: v.array(vEscalationUnit)
});

export const vInternalHistogramBucket = v.object({
    checks: vScreenedInt,
    key: v.string(),
    label: v.string(),
    share: vScreenedFloat
});

export const vInternalHistogram = v.object({
    boundaries: v.array(v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647'))),
    buckets: v.array(vInternalHistogramBucket),
    k_threshold: v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    period: vPeriodDto,
    scope: vScopeDto,
    total: vScreenedInt
});

/**
 * A count and a mean, the pair every section publishes.
 */
export const vInternalPair = v.object({
    avg_originality: vScreenedFloat,
    checks: vScreenedInt
});

export const vInternalBreakdown = v.object({
    items: v.array(vInternalBreakdownItem),
    k_threshold: v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    period: vPeriodDto,
    scope: vScopeDto,
    total: vInternalPair
});

export const vInternalPreviousPeriod = v.object({
    avg_originality: vScreenedFloat,
    escalated: vScreenedInt,
    period: vPeriodDto,
    total_checks: vScreenedInt
});

export const vInternalSummary = v.object({
    avg_originality: vScreenedFloat,
    below_threshold: vScreenedInt,
    below_threshold_share: vScreenedFloat,
    coverage: v.nullish(vScreenedFloat),
    escalated: vScreenedInt,
    k_threshold: v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    period: vPeriodDto,
    previous: vInternalPreviousPeriod,
    scope: vScopeDto,
    total_checks: vScreenedInt
});

export const vInternalTimeseriesPoint = v.object({
    avg_originality: vScreenedFloat,
    checks: vScreenedInt,
    month: v.string()
});

export const vInternalTimeseries = v.object({
    k_threshold: v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    months: v.array(vInternalTimeseriesPoint),
    period: vPeriodDto,
    scope: vScopeDto
});

export const vInternalYoyYear = v.object({
    academic_year: v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    avg_originality: vScreenedFloat,
    checks: vScreenedInt,
    label: v.string()
});

export const vInternalYoy = v.object({
    k_threshold: v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    period: vPeriodDto,
    scope: vScopeDto,
    total: vInternalPair,
    years: v.array(vInternalYoyYear)
});

export const vMatrixDepartment = v.object({
    avg_originality: vScreenedFloat,
    checks: vScreenedInt,
    code: v.string(),
    name_en: v.string(),
    name_kk: v.string(),
    name_ru: v.string()
});

export const vMatrixFaculty = v.object({
    code: v.string(),
    departments: v.array(vMatrixDepartment),
    name_en: v.string(),
    name_kk: v.string(),
    name_ru: v.string(),
    total: vInternalPair
});

export const vDepartmentsMatrix = v.object({
    faculties: v.array(vMatrixFaculty),
    k_threshold: v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    period: vPeriodDto,
    scope: vScopeDto,
    total: vInternalPair
});

/**
 * Count and mean originality of one group - the pair every section publishes.
 */
export const vMetricPair = v.object({
    avg_originality: vScreenedFloat,
    checks: vScreenedInt
});

export const vBreakdownResponse = v.object({
    items: v.array(vBreakdownItemDto),
    k_threshold: v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    period: vPeriodDto,
    suppressed_groups: v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    total: vMetricPair
});

export const vPublicStatus = v.object({
    contour: v.string(),
    example_metric: vScreenedInt
});

export const vRecheckUnit = v.object({
    code: v.string(),
    improved: vScreenedInt,
    name_ru: v.string(),
    recheck_share: vScreenedFloat,
    works_rechecked: vScreenedInt,
    works_total: vScreenedInt
});

export const vInternalRechecks = v.object({
    improved: vScreenedInt,
    improved_share: vScreenedFloat,
    k_threshold: v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    period: vPeriodDto,
    recheck_share: vScreenedFloat,
    scope: vScopeDto,
    units: v.array(vRecheckUnit),
    works_rechecked: vScreenedInt,
    works_total: vScreenedInt
});

export const vSummaryDeltaDto = v.object({
    avg_originality: vScreenedFloat,
    below_threshold_share: vScreenedFloat,
    escalated: vScreenedInt,
    total_checks: vScreenedInt
});

/**
 * The same KPIs one year earlier, plus the deltas the cards render.
 */
export const vPreviousPeriodDto = v.object({
    avg_originality: vScreenedFloat,
    below_threshold: vScreenedInt,
    below_threshold_share: vScreenedFloat,
    delta: vSummaryDeltaDto,
    escalated: vScreenedInt,
    period: vPeriodDto,
    total_checks: vScreenedInt
});

export const vSummaryResponse = v.object({
    avg_originality: vScreenedFloat,
    below_threshold: vScreenedInt,
    below_threshold_share: vScreenedFloat,
    coverage: v.nullish(vScreenedFloat),
    escalated: vScreenedInt,
    k_threshold: v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    period: vPeriodDto,
    previous: vPreviousPeriodDto,
    suppressed_groups: v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    total_checks: vScreenedInt
});

export const vTimeseriesPointDto = v.object({
    avg_originality: vScreenedFloat,
    checks: vScreenedInt,
    escalated: vScreenedInt,
    month: v.string(),
    rechecks: vScreenedInt
});

export const vTimeseriesResponse = v.object({
    k_threshold: v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    months: v.array(vTimeseriesPointDto),
    period: vPeriodDto,
    suppressed_groups: v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647'))
});

export const vUsageMonth = v.object({
    active_reviewers: vScreenedInt,
    avg_check_seconds: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647'))),
    month: v.string(),
    reported_active_users: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')))
});

export const vInternalUsage = v.object({
    k_threshold: v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    months: v.array(vUsageMonth),
    period: vPeriodDto,
    scope: vScopeDto
});

export const vUsageStatDto = v.object({
    active_users: v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    avg_check_seconds: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647'))),
    period_month: v.string()
});

export const vUsageStatUpsert = v.strictObject({
    active_users: v.optional(v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647'))),
    avg_check_seconds: v.nullish(v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647'))),
    period_month: v.string()
});

export const vUsageStatsResponse = v.object({
    items: v.array(vUsageStatDto)
});

export const vWorkTypeRuleDto = v.object({
    active: v.boolean(),
    id: v.pipe(v.number(), v.integer()),
    pattern: v.string(),
    priority: v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    work_type_code: v.string()
});

export const vWorkTypeRuleUpsert = v.strictObject({
    active: v.optional(v.boolean()),
    pattern: v.string(),
    priority: v.optional(v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647'))),
    work_type_code: v.string()
});

export const vWorkTypeRulesResponse = v.object({
    items: v.array(vWorkTypeRuleDto)
});

export const vYoyYearDto = v.object({
    academic_year: v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    avg_originality: vScreenedFloat,
    checks: vScreenedInt,
    label: v.string()
});

export const vYoyResponse = v.object({
    k_threshold: v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    period: vPeriodDto,
    suppressed_groups: v.pipe(v.number(), v.integer(), v.minValue(0), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')),
    total: vMetricPair,
    years: v.array(vYoyYearDto)
});

export const vListAliasesResponse = vAliasesResponse;

export const vUpsertAliasBody = vAliasUpsert;

export const vUpsertAliasResponse = vAliasesResponse;

export const vDeleteAliasPath = v.object({
    id: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))
});

/**
 * removed
 */
export const vDeleteAliasResponse = v.void();

export const vAuditQuery = v.object({
    user_id: v.optional(v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))),
    role: v.optional(v.string()),
    action: v.optional(v.string()),
    section: v.optional(v.string()),
    from: v.optional(v.string()),
    to: v.optional(v.string()),
    limit: v.optional(v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))),
    offset: v.optional(v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')))
});

export const vAuditResponse2 = vAuditResponse;

export const vListDictionaryPath = v.object({
    kind: v.string()
});

export const vListDictionaryResponse = vDictionaryResponse;

export const vUpsertDictionaryBody = vDictionaryUpsert;

export const vUpsertDictionaryPath = v.object({
    kind: v.string()
});

export const vUpsertDictionaryResponse = vDictionaryResponse;

export const vDeleteDictionaryPath = v.object({
    kind: v.string(),
    code: v.string()
});

/**
 * removed
 */
export const vDeleteDictionaryResponse = v.void();

export const vListEthicsQuery = v.object({
    from_year: v.optional(v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647'))),
    to_year: v.optional(v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')))
});

export const vListEthicsResponse = vEthicsCasesResponse;

export const vCreateEthicsBody = vEthicsCaseUpsert;

export const vCreateEthicsResponse = vEthicsCasesResponse;

export const vDeleteEthicsPath = v.object({
    id: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))
});

/**
 * removed
 */
export const vDeleteEthicsResponse = v.void();

export const vUpdateEthicsBody = vEthicsCaseUpsert;

export const vUpdateEthicsPath = v.object({
    id: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))
});

export const vUpdateEthicsResponse = vEthicsCasesResponse;

export const vListBatchesQuery = v.object({
    limit: v.optional(v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))),
    offset: v.optional(v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')))
});

export const vListBatchesResponse = vBatchesResponse;

export const vGetBatchPath = v.object({
    id: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))
});

export const vGetBatchResponse = vBatchDetailDto;

export const vRunIngestBody = vRunIngestRequest;

/**
 * run started
 */
export const vRunIngestResponse2 = vRunIngestResponse;

export const vListSourcesResponse = vSourcesResponse;

export const vCreateSourceBody = vSourceUpsert;

export const vCreateSourceResponse = vSourcesResponse;

export const vDeleteSourcePath = v.object({
    id: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))
});

/**
 * removed
 */
export const vDeleteSourceResponse = v.void();

export const vUpdateSourceBody = vSourceUpsert;

export const vUpdateSourcePath = v.object({
    id: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))
});

export const vUpdateSourceResponse = vSourcesResponse;

export const vListInitiatorRulesResponse = vInitiatorRulesResponse;

export const vCreateInitiatorRuleBody = vInitiatorRuleUpsert;

export const vCreateInitiatorRuleResponse = vInitiatorRulesResponse;

export const vDeleteInitiatorRulePath = v.object({
    id: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))
});

/**
 * removed
 */
export const vDeleteInitiatorRuleResponse = v.void();

export const vUpdateInitiatorRuleBody = vInitiatorRuleUpsert;

export const vUpdateInitiatorRulePath = v.object({
    id: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))
});

export const vUpdateInitiatorRuleResponse = vInitiatorRulesResponse;

export const vPingResponse = vAdminPing;

export const vListReportsQuery = v.object({
    limit: v.optional(v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))),
    offset: v.optional(v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')))
});

export const vListReportsResponse = vAdminReportsResponse;

export const vGenerateReportBody = vGenerateReportRequest;

/**
 * generated
 */
export const vGenerateReportResponse = vAdminReportsResponse;

export const vPublishReportPath = v.object({
    id: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))
});

/**
 * published
 */
export const vPublishReportResponse = v.void();

export const vUnpublishReportPath = v.object({
    id: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))
});

/**
 * withdrawn
 */
export const vUnpublishReportResponse = v.void();

export const vRevokeRoleBody = vRoleGrantRequest;

/**
 * revoked
 */
export const vRevokeRoleResponse = v.void();

export const vListRolesQuery = v.object({
    limit: v.optional(v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))),
    offset: v.optional(v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')))
});

export const vListRolesResponse = vRolesResponse;

export const vGrantRoleBody = vRoleGrantRequest;

export const vGrantRoleResponse = vRolesResponse;

export const vSettingsResponse2 = vSettingsResponse;

export const vUpdateSettingsBody = vSettingsUpdate;

export const vUpdateSettingsResponse = vSettingsResponse;

export const vListStaffUnitsQuery = v.object({
    limit: v.optional(v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))),
    offset: v.optional(v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807')))
});

export const vListStaffUnitsResponse = vStaffUnitsResponse;

export const vUpsertStaffUnitBody = vStaffUnitUpsert;

export const vUpsertStaffUnitResponse = vStaffUnitsResponse;

export const vDeleteStaffUnitPath = v.object({
    hmac: v.string()
});

/**
 * removed
 */
export const vDeleteStaffUnitResponse = v.void();

export const vDeleteSubmissionTotalBody = vSubmissionTotalUpsert;

/**
 * removed
 */
export const vDeleteSubmissionTotalResponse = v.void();

export const vListSubmissionTotalsQuery = v.object({
    from_year: v.optional(v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647'))),
    to_year: v.optional(v.pipe(v.number(), v.integer(), v.minValue(-2147483648, 'Invalid value: Expected int32 to be >= -2147483648'), v.maxValue(2147483647, 'Invalid value: Expected int32 to be <= 2147483647')))
});

export const vListSubmissionTotalsResponse = vSubmissionTotalsResponse;

export const vUpsertSubmissionTotalBody = vSubmissionTotalUpsert;

export const vUpsertSubmissionTotalResponse = vSubmissionTotalsResponse;

export const vDeleteUsageStatBody = vUsageStatUpsert;

/**
 * removed
 */
export const vDeleteUsageStatResponse = v.void();

export const vListUsageStatsQuery = v.object({
    from: v.optional(v.string()),
    to: v.optional(v.string())
});

export const vListUsageStatsResponse = vUsageStatsResponse;

export const vUpsertUsageStatBody = vUsageStatUpsert;

export const vUpsertUsageStatResponse = vUsageStatsResponse;

export const vListWorkTypeRulesResponse = vWorkTypeRulesResponse;

export const vCreateWorkTypeRuleBody = vWorkTypeRuleUpsert;

export const vCreateWorkTypeRuleResponse = vWorkTypeRulesResponse;

export const vDeleteWorkTypeRulePath = v.object({
    id: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))
});

/**
 * removed
 */
export const vDeleteWorkTypeRuleResponse = v.void();

export const vUpdateWorkTypeRuleBody = vWorkTypeRuleUpsert;

export const vUpdateWorkTypeRulePath = v.object({
    id: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))
});

export const vUpdateWorkTypeRuleResponse = vWorkTypeRulesResponse;

export const vLoginBody = vLoginRequest;

/**
 * session established
 */
export const vLoginResponse = vMeResponse;

/**
 * session ended
 */
export const vLogoutResponse2 = vLogoutResponse;

export const vMeResponse2 = vMeResponse;

export const vDepartmentsMatrixQuery = v.object({
    period: v.optional(v.string()),
    from: v.optional(v.string()),
    to: v.optional(v.string()),
    faculty: v.optional(v.string()),
    department: v.optional(v.string()),
    program: v.optional(v.string()),
    work_type: v.optional(v.string()),
    status: v.optional(v.string()),
    initiator: v.optional(v.string())
});

export const vDepartmentsMatrixResponse = vDepartmentsMatrix;

export const vEscalationsQuery = v.object({
    period: v.optional(v.string()),
    from: v.optional(v.string()),
    to: v.optional(v.string()),
    faculty: v.optional(v.string()),
    department: v.optional(v.string()),
    program: v.optional(v.string()),
    work_type: v.optional(v.string()),
    status: v.optional(v.string()),
    initiator: v.optional(v.string())
});

export const vEscalationsResponse = vInternalEscalations;

/**
 * the filter state to export; an empty body means the default period
 */
export const vInternalExportBody = vInternalFilterQuery;

export const vInternalExportQuery = v.object({
    format: v.picklist(['pdf', 'xlsx']),
    locale: v.optional(v.string())
});

/**
 * the rendered report
 */
export const vInternalExportResponse = v.string();

export const vHistogramQuery = v.object({
    period: v.optional(v.string()),
    from: v.optional(v.string()),
    to: v.optional(v.string()),
    faculty: v.optional(v.string()),
    department: v.optional(v.string()),
    program: v.optional(v.string()),
    work_type: v.optional(v.string()),
    status: v.optional(v.string()),
    initiator: v.optional(v.string())
});

export const vHistogramResponse2 = vInternalHistogram;

export const vPing2Response = vInternalPing;

export const vRechecksQuery = v.object({
    period: v.optional(v.string()),
    from: v.optional(v.string()),
    to: v.optional(v.string()),
    faculty: v.optional(v.string()),
    department: v.optional(v.string()),
    program: v.optional(v.string()),
    work_type: v.optional(v.string()),
    status: v.optional(v.string()),
    initiator: v.optional(v.string())
});

export const vRechecksResponse = vInternalRechecks;

export const vSummaryQuery = v.object({
    period: v.optional(v.string()),
    from: v.optional(v.string()),
    to: v.optional(v.string()),
    faculty: v.optional(v.string()),
    department: v.optional(v.string()),
    program: v.optional(v.string()),
    work_type: v.optional(v.string()),
    status: v.optional(v.string()),
    initiator: v.optional(v.string())
});

export const vSummaryResponse2 = vInternalSummary;

export const vTimeseriesQuery = v.object({
    period: v.optional(v.string()),
    from: v.optional(v.string()),
    to: v.optional(v.string()),
    faculty: v.optional(v.string()),
    department: v.optional(v.string()),
    program: v.optional(v.string()),
    work_type: v.optional(v.string()),
    status: v.optional(v.string()),
    initiator: v.optional(v.string())
});

export const vTimeseriesResponse2 = vInternalTimeseries;

export const vUsageQuery = v.object({
    period: v.optional(v.string()),
    from: v.optional(v.string()),
    to: v.optional(v.string()),
    faculty: v.optional(v.string()),
    department: v.optional(v.string()),
    program: v.optional(v.string()),
    work_type: v.optional(v.string()),
    status: v.optional(v.string()),
    initiator: v.optional(v.string())
});

export const vUsageResponse = vInternalUsage;

export const vWorkTypesQuery = v.object({
    period: v.optional(v.string()),
    from: v.optional(v.string()),
    to: v.optional(v.string()),
    faculty: v.optional(v.string()),
    department: v.optional(v.string()),
    program: v.optional(v.string()),
    work_type: v.optional(v.string()),
    status: v.optional(v.string()),
    initiator: v.optional(v.string())
});

export const vWorkTypesResponse = vInternalBreakdown;

export const vYoyQuery = v.object({
    period: v.optional(v.string()),
    from: v.optional(v.string()),
    to: v.optional(v.string()),
    faculty: v.optional(v.string()),
    department: v.optional(v.string()),
    program: v.optional(v.string()),
    work_type: v.optional(v.string()),
    status: v.optional(v.string()),
    initiator: v.optional(v.string())
});

export const vYoyResponse2 = vInternalYoy;

/**
 * the filter state to export; an empty body means the default period
 */
export const vPublicExportBody = vPublicFilterQuery;

export const vPublicExportQuery = v.object({
    format: v.picklist(['pdf', 'xlsx']),
    locale: v.optional(v.string())
});

/**
 * the rendered report
 */
export const vPublicExportResponse = v.string();

export const vFacultiesQuery = v.object({
    period: v.optional(v.string()),
    from: v.optional(v.string()),
    to: v.optional(v.string()),
    faculty: v.optional(v.string()),
    work_type: v.optional(v.string())
});

export const vFacultiesResponse = vBreakdownResponse;

export const vHistogram2Query = v.object({
    period: v.optional(v.string()),
    from: v.optional(v.string()),
    to: v.optional(v.string()),
    faculty: v.optional(v.string()),
    work_type: v.optional(v.string())
});

export const vHistogram2Response = vHistogramResponse;

export const vReportsResponse2 = vReportsResponse;

export const vDownloadPath = v.object({
    id: v.pipe(v.union([
        v.number(),
        v.string(),
        v.bigint()
    ]), v.transform(x => BigInt(x)), v.minValue(BigInt('-9223372036854775808'), 'Invalid value: Expected int64 to be >= -9223372036854775808'), v.maxValue(BigInt('9223372036854775807'), 'Invalid value: Expected int64 to be <= 9223372036854775807'))
});

export const vDownloadQuery = v.object({
    format: v.picklist(['pdf', 'xlsx'])
});

/**
 * the published file
 */
export const vDownloadResponse = v.string();

export const vStatusResponse = vPublicStatus;

export const vSummary2Query = v.object({
    period: v.optional(v.string()),
    from: v.optional(v.string()),
    to: v.optional(v.string()),
    faculty: v.optional(v.string()),
    work_type: v.optional(v.string())
});

export const vSummary2Response = vSummaryResponse;

export const vTimeseries2Query = v.object({
    period: v.optional(v.string()),
    from: v.optional(v.string()),
    to: v.optional(v.string()),
    faculty: v.optional(v.string()),
    work_type: v.optional(v.string())
});

export const vTimeseries2Response = vTimeseriesResponse;

export const vWorkTypes2Query = v.object({
    period: v.optional(v.string()),
    from: v.optional(v.string()),
    to: v.optional(v.string()),
    faculty: v.optional(v.string()),
    work_type: v.optional(v.string())
});

export const vWorkTypes2Response = vBreakdownResponse;

export const vYoy2Query = v.object({
    period: v.optional(v.string()),
    from: v.optional(v.string()),
    to: v.optional(v.string()),
    faculty: v.optional(v.string()),
    work_type: v.optional(v.string())
});

export const vYoy2Response = vYoyResponse;

export const vHealthzResponse = vHealth;

export const vReadyzResponse = vHealth;
