import { createIsomorphicFn } from "@tanstack/react-start"
import { getRequestHeader } from "@tanstack/react-start/server"
import * as v from "valibot"

import { client } from "../api/client.gen"
import { Public } from "../api/sdk.gen"

import { filenameFromDisposition } from "./download"
import type {
  BreakdownResponse,
  HistogramResponse,
  Problem,
  ReportsResponse,
  SummaryResponse,
  TimeseriesResponse,
  YoyResponse,
} from "../api/types.gen"
import {
  vBreakdownResponse,
  vHistogramResponse,
  vReportsResponse,
  vSummaryResponse,
  vTimeseriesResponse,
  vYoyResponse,
} from "../api/valibot.gen"

/**
 * The one seam between the application and the generated client
 * (`src/api/`, DO NOT EDIT - regenerated by `vp run gen:api`).
 *
 * Everything server-side enters through here: base-URL resolution, RFC 7807
 * error mapping, and the environment-dependent response validation ADR-006
 * prescribes. No module outside `src/api/` may call `fetch` directly.
 */

/* ── Base URL ─────────────────────────────────────────────────────────────── */

/**
 * The browser always uses its own origin, so the generated absolute paths
 * (`/api/public/summary`) need no base URL and never cross an origin: nginx
 * serves `/api` in production (ARCHITECTURE §5.6) and the Vite dev-server proxy
 * serves it in development.
 *
 * SSR cannot do that - Node's `fetch` requires an origin - so the server side
 * resolves `API_ORIGIN` (the internal address of the Rust API), then an
 * explicit `VITE_API_BASE`, then the local development default, which is also
 * where the dev-server proxy points. Documented in `src/api/README.md`.
 */
const DEV_API_ORIGIN = "http://127.0.0.1:8080"

function resolveBaseUrl(): string {
  if (!import.meta.env.SSR) return import.meta.env.VITE_API_BASE ?? ""
  const fromProcess =
    typeof process === "undefined" ? undefined : process.env.API_ORIGIN
  return fromProcess ?? import.meta.env.VITE_API_BASE ?? DEV_API_ORIGIN
}

client.setConfig({ baseUrl: resolveBaseUrl() })

/* ── Session cookie on the SSR hop ────────────────────────────────────────── */

/**
 * The internal and admin contours authenticate with the `np_session` cookie.
 * In the browser that rides along automatically (same origin); during SSR the
 * Node renderer is a *third* party between the browser and Rust, so the
 * incoming request's cookie header has to be forwarded explicitly or every
 * loader would render a 401 and the page would only fill in after hydration.
 *
 * `createIsomorphicFn` is what keeps `@tanstack/react-start/server` out of the
 * browser bundle: the Start plugin erases the `.server()` branch - and its
 * import - from the client build.
 */
const forwardedCookie = createIsomorphicFn()
  .server(() => getRequestHeader("cookie"))
  .client(() => undefined)

client.interceptors.request.use((request: Request) => {
  const cookie = forwardedCookie()
  // `Headers.set('cookie')` is a no-op behind the browser's forbidden-header
  // guard; this branch only ever runs under Node, where it is permitted.
  if (cookie !== undefined && cookie !== "")
    request.headers.set("cookie", cookie)
  return request
})

/* ── Errors ───────────────────────────────────────────────────────────────── */

/**
 * A failed public request. Carries the RFC 7807 body when the server sent one,
 * so a section's error boundary can show `title`/`detail` instead of a stack.
 */
export class ApiError extends Error {
  readonly status: number
  readonly problem: Problem | undefined

  constructor(section: string, status: number, problem: Problem | undefined) {
    super(problem?.detail ?? problem?.title ?? `${section}: HTTP ${status}`)
    this.name = "ApiError"
    this.status = status
    this.problem = problem
  }
}

export function isProblem(value: unknown): value is Problem {
  return (
    typeof value === "object" &&
    value !== null &&
    "title" in value &&
    "status" in value
  )
}

/* ── Response validation ──────────────────────────────────────────────────── */

/**
 * ADR-006: parse responses against the generated Valibot schemas while
 * developing and under test - a contract violation then fails at the boundary
 * with a readable path - and trust the server in production builds, where the
 * contract has already been gated by `gen:api:check` and the backend tests.
 */
const VALIDATE_RESPONSES =
  import.meta.env.DEV || import.meta.env.MODE === "test"

export type Fetched<TData> = {
  data?: TData | undefined
  error?: unknown
  response?: Response | undefined
}

export async function fetchScreened<TData>(
  section: string,
  call: () => Promise<Fetched<TData>>,
  schema: v.GenericSchema
): Promise<TData> {
  const { data, error, response } = await call()
  if (error !== undefined || data === undefined || response?.ok !== true) {
    throw new ApiError(
      section,
      response?.status ?? 0,
      isProblem(error) ? error : undefined
    )
  }
  if (VALIDATE_RESPONSES) {
    // Parsed for the check only: the generated TypeScript type is what the
    // application reads, so a passing parse must not re-shape the value.
    v.parse(schema, data)
  }
  return data
}

/**
 * A mutation whose success is `204 No Content` (every admin delete, publish and
 * revoke). There is no body to validate - only the status decides.
 */
export async function fetchVoid(
  section: string,
  call: () => Promise<Fetched<unknown>>
): Promise<void> {
  const { error, response } = await call()
  if (error !== undefined || response?.ok !== true) {
    throw new ApiError(
      section,
      response?.status ?? 0,
      isProblem(error) ? error : undefined
    )
  }
}

/**
 * The header every mutating request on the internal and admin contours carries
 * (double-submit CSRF; the token comes from `/api/auth/me`).
 */
export function csrfHeaders(csrf: string): Record<string, string> {
  return { "x-csrf-token": csrf }
}

/** Origin the browser should address the API on - see {@link resolveBaseUrl}. */
export function apiBaseUrl(): string {
  return import.meta.env.VITE_API_BASE ?? ""
}

/* ── Public contour ───────────────────────────────────────────────────────── */

/**
 * Query string every filtered public endpoint accepts (contract §4.3).
 * Derived from the SDK signature rather than from a named type: the two
 * contours share operation ids, so the generator suffixes the *type* names
 * (`Summary2Data`) in an order that depends on the document.
 */
export type PublicQuery = NonNullable<
  NonNullable<Parameters<typeof Public.summary>[0]>["query"]
>

/** The two export formats, straight off the contract. */
export type ExportFormat = NonNullable<
  Parameters<typeof Public.publicExport>[0]
>["query"]["format"]

export const publicApi = {
  summary: (
    query: PublicQuery,
    signal?: AbortSignal
  ): Promise<SummaryResponse> =>
    fetchScreened(
      "summary",
      () => Public.summary({ query, signal }),
      vSummaryResponse
    ),

  timeseries: (
    query: PublicQuery,
    signal?: AbortSignal
  ): Promise<TimeseriesResponse> =>
    fetchScreened(
      "timeseries",
      () => Public.timeseries({ query, signal }),
      vTimeseriesResponse
    ),

  workTypes: (
    query: PublicQuery,
    signal?: AbortSignal
  ): Promise<BreakdownResponse> =>
    fetchScreened(
      "work-types",
      () => Public.workTypes({ query, signal }),
      vBreakdownResponse
    ),

  faculties: (
    query: PublicQuery,
    signal?: AbortSignal
  ): Promise<BreakdownResponse> =>
    fetchScreened(
      "faculties",
      () => Public.faculties({ query, signal }),
      vBreakdownResponse
    ),

  histogram: (
    query: PublicQuery,
    signal?: AbortSignal
  ): Promise<HistogramResponse> =>
    fetchScreened(
      "histogram",
      () => Public.histogram({ query, signal }),
      vHistogramResponse
    ),

  yoy: (query: PublicQuery, signal?: AbortSignal): Promise<YoyResponse> =>
    fetchScreened("yoy", () => Public.yoy({ query, signal }), vYoyResponse),

  reports: (signal?: AbortSignal): Promise<ReportsResponse> =>
    fetchScreened(
      "reports",
      () => Public.reports({ signal }),
      vReportsResponse
    ),

  /**
   * TZ §4.4 - the filtered public view, as a file
   * (`POST /api/public/export?format=pdf|xlsx`).
   *
   * Unlike the internal export there is no session and therefore no CSRF token
   * to send: the endpoint is anonymous, it writes no audit row (there is no
   * identity to record) and every cell it renders is already screened. The
   * filters travel in the body exactly as the URL describes them, so the file
   * and the page on screen cover the same period and the same dimensions.
   */
  export: async (
    query: PublicQuery,
    format: ExportFormat,
    locale: string,
    signal?: AbortSignal
  ): Promise<{ blob: Blob; filename: string }> => {
    const { data, error, response } = await Public.publicExport({
      body: query,
      query: { format, locale },
      parseAs: "blob",
      signal,
    })
    if (error !== undefined || data === undefined || response?.ok !== true) {
      throw new ApiError(
        "public/export",
        response?.status ?? 0,
        isProblem(error) ? error : undefined
      )
    }
    return {
      blob: data,
      filename:
        filenameFromDisposition(response.headers.get("content-disposition")) ??
        `noplagiat.${format}`,
    }
  },
}

/**
 * Browser URL of a published report file
 * (`GET /api/public/reports/{id}/download?format=pdf|xlsx`).
 *
 * A download is a navigation, not a fetch, so the link is built here rather
 * than issued through the SDK - but the path still comes from the contract and
 * the origin rule is the one above: same-origin in the browser, explicit only
 * when `VITE_API_BASE` overrides it.
 */
export function reportDownloadUrl(id: number, format: string): string {
  return `${apiBaseUrl()}/api/public/reports/${String(id)}/download?format=${encodeURIComponent(format)}`
}
